### ISSUE TITLE
Numpy like slice

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/swift-apis#101]
Hey, I am having a lot of fun learning Swift via S4TF and reading the new features you guys are implementing, the project seems to be moving very fast :) 

I was a little worried when I tried to do a simple slice and found out that it was more complicated than I expected. To try to make things more familiar I implemented a `Slice` enum and extended the `Tensor` struct with a new `slice` method that takes `Slice...` args in such a way that it behaves like numpy. Here is an example with its corresponding python equivalent:

```swift
x.slice(.all, .at(1))  // x[:, 1]
x.slice(.all, .upto(3))  // x[:, :3]
x.slice(.all, .from(2))  // x[:, 2:]
x.slice(.all, .slice(1, 5))  // x[:, 1:5]
x.slice(.rest, .at(0))  // x[..., 0]
```
It works for Tensors of any shape and any slice combination. It would be awsome if swift eventually supported complex subscripting so it could be implemented natively like this:
```swift
x[..., 1]  // x[:, 1]
x[..., ..<3]  // x[:, :3]
x[..., 2...]  // x[:, 2:]
x[..., 1..<5]  // x[:, 1:5]
x[???, 0]  // x[..., 0]  <-- no idea about this one
```
I thought this might be useful to others or maybe it can even get integrated into to project. Here is the code if you are interested:

```swift

enum Slice : Equatable {
    case slice(Int, Int)
    case at(Int)
    case from(Int)
    case upto(Int)
    case all
    case rest

    func get_range(_ n: Int) -> (Int, Int) {
        var low: Int = 0
        var high: Int = n

        switch self {
            case .slice(let _low, let _high):
                low = _low
                high = _high
            case .at(let value):
                low = value
                high = value + 1
            case .from(let _low):
                low = _low
            case .upto(let _high):
                high = _high
            default:
                break 
        }


        if low < 0 {
            low += n
        }

        if high < 0 {
            high += n
        }


        return (low, high)
    }
}

enum SliceError : Error {
    case MultipleRest
    case TooManySlices
}

extension Tensor {

    func slice(_ slices: Slice...) throws -> Tensor {
        var slices = slices
        let ndim = Int(self.shape.count)

        if slices.count > ndim {
            throw SliceError.TooManySlices
        }

        if slices.count < ndim && !slices.contains(.rest) {
            slices.append(.rest)
        }

        let restCount = slices.filter { $0 == .rest }.count
        let notRestCount = slices.count - restCount
        let restExpand = ndim - notRestCount

        if restCount > 1 {
            throw SliceError.MultipleRest
        }

        if restExpand > 0 {
            let allSlices = Array(repeating: Slice.all, count: restExpand)
            let idx = slices.firstIndex(of: .rest)!

            slices = slices[..<idx] + allSlices + slices[(idx+1)...]
        }

        var lowerBounds: [Int32] = []
        var upperBounds: [Int32] = []

        for (slice, n) in zip(slices, self.shape.dimensions) {
            var (lower, upper) = slice.get_range(Int(n))
            
            if lower < 0 {
                lower = 0
            }

            if upper > n {
                upper = Int(n)
            }
            
            lowerBounds.append(Int32(lower))
            upperBounds.append(Int32(upper))
        }

        let squeezeDims = slices.enumerated()
            .filter { 
                if case .at(_) = $1 { return true } 
                else { return false } 
            }
            .map { $0.0 }
            .reversed()
        
        var output = self.slice(lowerBounds: lowerBounds, upperBounds: upperBounds)

        for i in squeezeDims {
            output = output.squeezingShape(at: Int32(i))
        }

        return output
    }
}
```

**Comment by rxwei** [comment]
Hi @cgarciae, thanks for bringing this up! Numpy-style advanced slicing/indexing in our tensor library just landed yesterday (PR https://github.com/apple/swift/pull/23684 by @eaplatanios). There's also a [discussion thread](https://groups.google.com/a/tensorflow.org/forum/#!msg/swift/LPDeqmFU8n4/RcseggTtBwAJ) on the mailing list.

In Swift, it is more common to define custom `subscript` operators as opposed to having a `slide` method to achieve advanced slicing.

**Comment by cgarciae** [comment]
@rxwei excellent! Looks like a very good step forward :)

I read that `v0.3` will land soon, will this be included? It would be great because currently I can try the new features, failed to build S4TF on my ubuntu machine. 

BTW: I reimplemented this via `subscript` and it looks great but you cannot `throw` so reporting problems to he user become dificult, even if the output was a `Tensor?` the user wouldn't know why it failed. What would be a "swifty" way of doing this?

**Comment by rxwei** [comment]
> I read that `v0.3` will land soon, will this be included? It would be great because currently I cant try the new features, failed to build S4TF on my ubuntu machine.

Yes, it will be included.



> BTW: I reimplemented this via `subscript` and it looks great but you cannot `throw` so reporting problems to he user become dificult, even if the output was a `Tensor?` the user wouldn't know why it failed. What would be a "swifty" way of doing this?

"Throwing subscripts" have been discussed in the Swift community before, but was never pushed to become a proposal. While it may be possible in the future, throwing slicing/indexing is not a common thing in Swift numerics and can make optimizations such as graph program extraction hard. I think runtime error handling for numerics in TensorFlow doesn't have to be in the base operator's type signature. It can be exposed either as a trailing-closure-based API, or a property projection like [`PythonObject.checking`](https://github.com/apple/swift/blob/162caae170af965920ff00c193447ca884d43c32/stdlib/public/Python/Python.swift#L409).

**Comment by cgarciae** [comment]
> While it may be possible in the future, throwing slicing/indexing is not a common thing in Swift numerics and can make optimizations such as graph program extraction hard. 

I see it makes sense. 

The current implementation of `slice` can crash but somehow doesn't `throw`, this is due to the same reason? This seems to contradict Swift's safety but I get that its preferable to help the compiler in the short term. 

Thanks for the comments!

**Comment by rxwei** [comment]
> The current implementation of `slice` can crash but somehow doesn't `throw`, this is due to the same reason? This seems to contradict Swift's safety but I get that its preferable to help the compiler in the short term.

This is because the TensorFlow backend is producing a runtime error, and Swift for TensorFlow's runtime doesn't handle it well yet. We definitely want to improve this over time!

**Comment by rxwei** [comment]
@cgarciae Is it okay if I close this issue, since numpy indexing is already in?

**Comment by dan-zheng** [comment]
Closing, as advanced index/slicing APIs were added in https://github.com/apple/swift/pull/23684.

There's no documentation currently, but the code is [here](https://github.com/apple/swift/blob/tensorflow-0.3/stdlib/public/TensorFlow/Ops.swift#L1718). Some examples:
```swift
import TensorFlow

// `TensorRange.ellipsis` is a placeholder for unspecified dimensions.
// It behaves like `Ellipsis` in NumPy slicing.
let tensor: Tensor<Float> = [[[0], [1], [2]], [[3], [4], [5]]]
print(tensor[TensorRange.ellipsis, 0])
// [[0.0, 1.0, 2.0],
//  [3.0, 4.0, 5.0]]

// `TensorRange.newAxis` inserts a new axis at its specified index.
print(tensor.shape)
print(tensor[TensorRange.newAxis, TensorRange.ellipsis].shape)
// [2, 3, 1]
// [1, 2, 3, 1]
```
