### ISSUE TITLE
cmake on MacOS - error: cannot load underlying module for 'XCTest'

### ISSUE THREAD

**Issue by mikowals** [tensorflow/swift-apis#1028]
Using the MacOS development toolchain from 2020-06-25 and the following commands:

    cmake -B out -G Ninja -S swift-apis -D USE_BUNDLED_X10=YES -D USE_BUNDLED_CTENSORFLOW=YES  \
                -D CMAKE_Swift_COMPILER=/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-06-25-a.xctoolchain/usr/bin/swiftc

    cmake --build out

Gets the output with error:

    [2/14] Linking Swift shared library Tests/ExperimentalTests/libExperimentalTests.dylib
    FAILED: Tests/ExperimentalTests/libExperimentalTests.dylib                
    Tests/ExperimentalTests/CMakeFiles/ExperimentalTests.dir/ComplexTests.swift.o  
    Tests/ExperimentalTests/CMakeFiles/ExperimentalTests.dir/XCTestManifests.swift.o swift/ExperimentalTests.swiftmodule
    : && /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-06-25-a.xctoolchain/usr/bin/swiftc -output-file-   
    map Tests/ExperimentalTests/CMakeFiles/ExperimentalTests.dir/Release/output-file-map.json -incremental -j 4 -emit-
    library -  o Tests/ExperimentalTests/libExperimentalTests.dylib -module-name ExperimentalTests -module-link-name   
    ExperimentalTests -emit-module -emit-module-path swift/ExperimentalTests.swiftmodule -emit-dependencies -
    DExperimentalTests_EXPORTS -O -sdk /Applications/Xcode-
    beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.16.sdk   -Xllvm -sil-inline-generics -
    Xllvm -sil-partial-specialization -I swift /Users/mikowals/projects/swift-source/swift-
    apis/Tests/ExperimentalTests/ComplexTests.swift /Users/mikowals/projects/swift-source/swift-
    apis/Tests/ExperimentalTests/XCTestManifests.swift  -Xlinker -install_name -Xlinker @rpath/libExperimentalTests.dylib  -L 
    /Users/mikowals/projects/swift-source/out/Sources/third_party/Experimental -Xlinker -rpath -Xlinker 
    /Users/mikowals/projects/swift-source/out/Sources/third_party/Experimental  
    Sources/third_party/Experimental/libExperimental.dylib  -lXCTest && :
    /Users/mikowals/projects/swift-source/swift-apis/Tests/ExperimentalTests/ComplexTests.swift:15:8: error: cannot load underlying module for 'XCTest'
    import XCTest
       ^
    [3/14] Linking Swift shared library Sources/Tensor/libTensor.dylib
    ninja: build stopped: subcommand failed.

**Comment by dan-zheng** [comment]
Does adding `-D BUILD_TESTING=NO` to the first CMake invocation fix the issue?

Building tests on macOS is not yet supported: https://github.com/tensorflow/swift-apis/pull/1029 updates README instructions with a clarification.

@compnerd: do you know if we can support building tests on macOS?

**Comment by mikowals** [comment]
Yes, adding `-D BUILD_TESTING=NO` works.  I didn't know testing on macOS wasn't supported.  Thanks for updating documentation.

**Comment by compnerd** [comment]
Yes, it’s possible.  There’s two options:
- build xctest from swift-corelibs-xctest (I’ve added that support)
- figure out what paths are needed for xctest to be used from Xcode

Both of these will require some additional flags (unless we package xctest in the toolchain).
