### ISSUE TITLE
Simple Optimizer Test

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/swift-apis#104]
Hey S4SF team, I am trying a very simple AD exercise using Adam. Since Adam requires a `Layer` type I created this very simple `Variable` struct that just holds the state. In this example I am just trying to minimize `x^2`:
```swift
import TensorFlow

struct Variable : Layer {
    var x: Float

    @differentiable
    func call(_ input: Float) -> Float {
        return x 
    }
}

var layer = Variable(x: 1.0)
let optimizer = Adam(for: layer)

let delta = layer.gradient { layer -> Float in
    let x = layer.x
    return x * x
}

print("Layer0:", layer)
print("Delta:", delta)

optimizer.update(&layer.allDifferentiableVariables, along: delta)

print("Layer1:", layer)
```
It appears that after update `layer` is not changing its `x` value:
```
Layer0: Variable(x: 1.0)
Delta: AllDifferentiableVariables(x: 2.0)
Layer1: Variable(x: 1.0)
```
Any idea why this not minimizing `x`?

**Comment by rxwei** [comment]
This is because standard optimizers [only work on tensors](https://github.com/tensorflow/swift-apis/blob/cfefd63fa60a55d1da1e2a412ed561eb3448e691/Sources/DeepLearning/Optimizer.swift#L93). To optimize general numeric values, you can currently use the manifold optimizer `RiemannSGD`.

**Comment by rxwei** [comment]
We plan to generalize out vector space protocols in order to be able to generalize these optimizers for all real vector types (`Float`, `Double`, `Float80`, `Tensor<BFloat16>`, `Tensor<Float16>`, etc). It's coming soon!

**Comment by cgarciae** [comment]
@rxwei thank for the info! But you will still need to create a Layer that uses these non-tensor types or will you be able to optimize other differentiable types like `Float` directly?

**Comment by rxwei** [comment]
Ideally we should be able to update any model with mixed parameters as long as the model conforms to `VectorNumeric`.
