### ISSUE TITLE
tf.contrib.layers.flatten(x) alternative function for TensorFlow V0.8.0

### ISSUE THREAD

**Issue by engrfaiz** [tensorflow/swift-apis#1105]
HI!
i am using Tensor flow 0.8.0 verison on Jetson TK1 with Cuda 6.5 on 32 bit arm architecture. For that i can't upgrade the Tensor Flow version and i am facing trouble in Flatten function 
x = tf.placeholder(dtype = tf.float32, shape = [None, 28, 28])
y = tf.placeholder(dtype = tf.int32, shape = [None])
images_flat = tf.contrib.layers.flatten(x)

The error i am getting at this point is
AttributeError: 'module' object has no attribute 'flatten'

is there any alternative to this function that may be supported in Tensor Flow V0.8

For more details about it, i am following this tutorial 
https://www.datacamp.com/community/tutorials/tensorflow-tutorial

Thanks

**Comment by BradLarson** [comment]
Unfortunately, I think you're asking about [Python-based TensorFlow](https://github.com/tensorflow/tensorflow), not Swift for TensorFlow, so we probably won't be able to answer you here.

I will say that TensorFlow is currently at version 2.3, and 0.8 is quite old, so it may be tricky to get support for that. I believe you should be able to use a newer version of TensorFlow on the TK1, which might make this easier.
