### ISSUE TITLE
'SinModel.AllDifferentiableVariables' and 'SinModel.CotangentVector' must be equivalent

### ISSUE THREAD

**Issue by tanmayb123** [tensorflow/swift-apis#115]
I'm working on an example with @brettkoonce, which is an RNN that can predict the `sin` function. This is the code I've got so far: https://gist.github.com/tanmayb123/366bc39caa18d71ed7ea0bd1d07e0a79

I'm getting this error:

```
main.swift:41:17: error: 'Adam' requires the types 'SinModel.AllDifferentiableVariables' and 'SinModel.CotangentVector' be equivalent
var optimizer = Adam<SinModel>(for: model)
                ^
Optimizer.swift:48:14: note: requirement specified as 'Model.AllDifferentiableVariables' == 'Model.CotangentVector' [with Model = SinModel]
public class Adam<Model: Layer>: Optimizer
             ^
```

I'm 99% sure this is being caused by the `RNN<Cell: RNNCell>` wrapper. How can we fix this?

I'd love your thoughts on this @rxwei.

**Comment by tanmayb123** [comment]
A quick thought on this: instead of having the `RNN` layer, couldn't we just add its functionality as an extension to the `RNNCell` protocol itself? That would make the protocol much more useful as well.

**Comment by brettkoonce** [comment]
Very fancy, @tanmayb123!  RiemannSGD produces a slightly different error, but I'm just changing things randomly:

    main.swift:41:17: error: type 'SinModel.TangentVector' does not conform to protocol 'VectorNumeric'
    var optimizer = RiemannSGD<SinModel, Float>(for: model, learningRate: 0.01)

**Comment by rxwei** [comment]
Hey @tanmayb123, sorry for the delayed response! We are close to being able to refresh and simplify all optimizer APIs by removing `AllDifferentiableVariables` and refactoring `Tensor`'s `VectorNumeric` conformance. I'll update this issue when the time comes.

**Comment by rxwei** [comment]
`AllDifferentiableVariables` has been deprecated.
