### ISSUE TITLE
swift-build errors

### ISSUE THREAD

**Issue by Shashi456** [tensorflow/swift-apis#124]
so I did build the master before and after, and `swift build` throws these errors : 
```
Compile Swift Module 'DeepLearning' (8 sources)
/home/paws/swift-apis/Sources/DeepLearning/Layer.swift:51:6: error: function result's 'pullback' type does not match 'inferring(from:)'
    @differentiating(inferring(from:))
     ^
/home/paws/swift-apis/Sources/DeepLearning/Layer.swift:54:38: note: 'pullback' does not have expected type '(Self.Output.CotangentVector) -> (Self.CotangentVector, Self.Input.CotangentVector)'
        -> (value: Output, pullback: (Output.TangentVector)
                                     ^~~~~~~~~~~~~~~~~~~~~~
/home/paws/swift-apis/Sources/DeepLearning/Layer.swift:46:10: note: 'inferring(from:)' defined here
    func inferring(from input: Input) -> Output {
         ^
/home/paws/swift-apis/Sources/DeepLearning/Layer.swift:1428:46: error: '_vjpCall(_:initialState:)' does not have expected type '<Cell where Cell : RNNCell> (RNN<Cell>) -> ([Cell.TimeStepInput], Cell.State) -> ([Cell.TimeStepOutput], (Array<Cell.TimeStepOutput.CotangentVector>.DifferentiableView) -> (RNN<Cell>.CotangentVector, Array<Cell.TimeStepInput.CotangentVector>.DifferentiableView))'
    @differentiable(wrt: (self, input), vjp: _vjpCall(_:initialState:))
                                             ^
/home/paws/swift-apis/Sources/DeepLearning/Layer.swift:77:22: error: cannot convert return expression of type '(Self.Output.CotangentVector) -> (Self.CotangentVector, Self.Input.CotangentVector)' to return type '(_) -> (layerGradient: _, inputGradient: _)'
        return (out, pullback)
                     ^~~~~~~~
                              as! (_) -> (layerGradient: _, inputGradient: _) 
```

**Comment by Shashi456** [comment]
oh wait, is this because i'm not on the nightly build and i'm on the tensorflow 3.1 build?

**Comment by dan-zheng** [comment]
Yes, this is because the 3.1 release is too outdated.
I'll release a new macOS toolchain today. Ubuntu nightly releases should work.

**Comment by Shashi456** [comment]
Sorry! I should've checked with nightly. I'll close the issue .

**Comment by dan-zheng** [comment]
Thanks again for your patience!

Out of curiosity: how do you develop `swift-apis`?
Do you use macOS or Ubuntu?
Do you build `swift-apis` with SwiftPM (`swift build`) using a toolchain from [`Installation.md`](https://github.com/tensorflow/swift/blob/master/Installation.md)?

Please let us know, so we can be informed about what workflows matter to you!

**Comment by Shashi456** [comment]
@dan-zheng I use a weird workflow xD. I have a windows system and windows has no viable swift support yet let alone s4tf. So, I found a workaround by managing a WSL - Windows subsystem for Linux, Linux18.04, since currently I mostly contribute to this repo. I build and test my repo within it. REPL doesn't work as of now.

**Comment by dan-zheng** [comment]
I see, that's interesting. Thanks for sharing 🙂
