### ISSUE TITLE
Rename and refactor convolution and pooling operators.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#138]
We've decided to rename existing convolution and pooling methods to something more approachable and discoverable, following precedents in other frameworks.

- [ ] Change method [`Tensor.convolved2D(withFilter:strides:padding:)`](https://github.com/tensorflow/swift-apis/blob/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9/Sources/DeepLearning/Operators.swift#L429) to a **top-level function** named **`conv2D(_:filter:strides:padding:)`**, taking the original `self` as a first argument.
- [ ] Change method [`Tensor.convolved3D(withFilter:strides:padding:)`](https://github.com/tensorflow/swift-apis/blob/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9/Sources/DeepLearning/Operators.swift#L457) to a **top-level function** named **`conv3D(_:filter:strides:padding:)`**, taking the original `self` as a first argument.
- [ ] Change method [`Tensor.maxPooled2D(kernelSize:strides:padding:)`](https://github.com/tensorflow/swift-apis/blob/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9/Sources/DeepLearning/Operators.swift#L483) to a **top-level function** named **`maxPool2D(_:filterSize:strides:padding:)`**, taking the original `self` as a first argument.
- [ ] Change method [`Tensor.maxPooled3D(kernelSize:strides:padding:)`](https://github.com/tensorflow/swift-apis/blob/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9/Sources/DeepLearning/Operators.swift#L510) to a **top-level function** named **`maxPool3D(_:filterSize:strides:padding:)`**, taking the original `self` as a first argument.
- [ ] Change method [`Tensor.avgPooled2D(kernelSize:strides:padding:)`](https://github.com/tensorflow/swift-apis/blob/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9/Sources/DeepLearning/Operators.swift#L483) to a **top-level function** named **`avgPool2D(_:filterSize:strides:padding:)`**, taking the original `self` as a first argument.
- [ ] Change method [`Tensor.avgPooled3D(kernelSize:strides:padding:)`](https://github.com/tensorflow/swift-apis/blob/ca8ac09285b0aaa7c6bbd08c375b1ba2b9e259e9/Sources/DeepLearning/Operators.swift#L563) to a **top-level function** named **`avgPool3D(_:filterSize:strides:padding:)`**, taking the original `self` as a first argument.

Note:
1. The new names we recommend are precisely described above. Further naming discussions are absolutely welcome, but will be preferable if delayed until July/August. These new names will make it into Swift for TensorFlow version 0.4.
2. These methods' derivatives (VJPs) will need to be changed to top-level functions as well.

**Comment by QuantumTCode** [comment]
I'll get to work on this, will post updates! =)

**Comment by rxwei** [comment]
Than you @QuantumTCode!

**Comment by Shashi456** [comment]
@rxwei why not just add aliases?

**Comment by rxwei** [comment]
> @rxwei why not just add aliases?

We never intended to keep names like `convolved2D`, `maxPooled2D` or `avgPooled2D` around. It's an artifact from early days of Swift for TensorFlow development. Since the project is very young, we would like to be able to improve and iterate quickly without baggage, and thus are not developing for user-facing backwards compatibility.

> Also, I think there is a lot of discussions to be had around naming conventions though.

Yep, you are right!

**Comment by rxwei** [comment]
Thank you @QuantumTCode!
