### ISSUE TITLE
Correct 'XCTAssertEqual(_:_:)' argument order.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#153]
#109 moved all TensorFlow APIs from apple/swift to this repository. However, some test assertions weren't updated because the argument order of the `expectEqual(_:_:)` function is different from that of `XCTAssertEqual(_:_:)` in that `expectEqual(_:_:)` expected the **first** argument to be the expected value, while `XCTAssertEqual(_:_:)` expected the **second** argument.

Here's a concrete example of a test assertion that used the old order:
https://github.com/tensorflow/swift-apis/blob/f194110443638f9f1a989307f21e43b653a5deb0/Tests/TensorFlowTests/OperatorTests/MathTests.swift#L22

It should be changed to:
```swift
XCTAssertEqual(x.sum(), Tensor(30))
```

### Task
Go through all tests (especially the ones in [`OperatorTests/`](https://github.com/tensorflow/swift-apis/tree/master/Tests/TensorFlowTests/OperatorTests)) and make sure `XCTAssertEqual(_:_:)` arguments are ordered correctly: The first argument should be the value to be tested, and the second argument should be the expected value.

**Comment by eaplatanios** [comment]
Good catch! I'll take this on tomorrow.

**Comment by rxwei** [comment]
Thanks Anthony! If you are too busy with existing PRs, parhaps @Shashi456 could help also.

**Comment by eaplatanios** [comment]
Thanks Richard, that would be great! Generally, I'll try to get as much in by Saturday because after that I am traveling to give a talk at NAACL and organize a workshop at ICML, right before proposing for my thesis :P I'll still be online after Saturday, but way busier for the next 2-3 weeks.

**Comment by Shashi456** [comment]
:o @eaplatanios All the best for the NAACL talk and ICML workshop, Absolutely amazing stuff.

and @rxwei yea alright, I'll take a look into this.

**Comment by eaplatanios** [comment]
Thanks @Shashi456! :)
