### ISSUE TITLE
Update README to reflect the new role and structure of the library

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#180]
The entire TensorFlow library has been moved from apple/swift to this repository, and the original `DeepLearning` module has been renamed to `TensorFlow`. One important remaining task is to change the README of this repo to describe the TensorFlow library as a whole with examples, and explain the structure of this new restructured repo. After that, send an email to swift@tensorflow.org summarizing this change. This task is on me later this week.

**Comment by Shashi456** [comment]
Also @rxwei, can you update the release on this repository when you update the readme? I know we have updated it on the mailing list and original s4tf release, but since this is main repo, it'd be good if we could do it on here as well.

**Comment by Shashi456** [comment]
@rxwei :P, Do you need help with this? Would love to create a small task list and help you out.

**Comment by Shashi456** [comment]
Would like to mention that windows development is now much easier with the introduction of Windows terminal. The only requirement is that you need ubuntu WSL and then install windows terminal (currently in preview), after which opening a ubuntu terminal and doing the usual steps. The only issue currently in windows is REPL doesn't work, but you may manually compile the files. As far as contributions are concerned, `swift build` and `swift test` work.

**Comment by Shashi456** [comment]
@rxwei sorry to call your attention to this again :p, but I think we need to update the readme. Could we start discussing what might be a part of it?

**Comment by rxwei** [comment]
Thanks for offering to help, @Shashi456!

Sorry for my delayed response as I'm traveling recently. I will handle this issue next week.
