### ISSUE TITLE
Conv2D Signature and initialization

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/swift-apis#181]
Reading the [Conv2D Documentation]( https://www.tensorflow.org/swift/api_docs/Structs/Conv2D) I noticed two issues:

1. The order of the arguments is not consistent across all the methods:
-  `(filter, bias, strides, padding, activation)` (which I prefer) 
- `(filter, bias, activation, strides, padding)`. 

2. The use of a canned initialization (glorotUniform) in the Api where you give only the seed / generator. I think that would be convenient to have a protocol that defines the initialization strategy for the Layer:
```
protocol InitializationStrategy {
   func Filter(TensorShape)
   func Bias(TensorShape)
}
```

```
    convenience init(
        filterShape: (Int, Int, Int),
        stride: Int = 1,
        padding: Padding = .valid,
        activation: @escaping Activation = identity,
        initializator: InitializationStrategy,
    ) {
        let filterTensorShape = TensorShape([
            filterShape.0, filterShape.1, filterShape.2])
        self.init(
            filter: initializator.Filter(shape: filterTensorShape),
            bias: initializator.Bias(shape: TensorShape([filterShape.2])),
            stride: stride,
            padding: padding,
            activation: activation)
    }
```
or even a more generic one to allow a single protocol for all initializations:
```
protocol InitializationStrategy {
   func Values(for: Strings, shape: TensorShape) -> Tensor<Float>
}
```
to be used it as 
```
       self.init(
            filter: initializator.Values( for: "Conv2D/filter", shape: filterTensorShape),
            bias: initializator.Values(for: "Conv2D/bias", shape: TensorShape([filterShape.2]))
        )
```

**Comment by Shashi456** [comment]
@mistobaan I think we all definitely agree that the layers aren't in the final shape that we'd want them to be. There are a variety of issues on layer improvement like #111, #54, #38. 

As far as general initialization is concerned currently the only initializer that is present is the glorot uniform. We will work on adding more in the future. Please do help in adding us more of these if you want to and send in a PR.

Thanks a lot for filing the issue. Allows us to keep this in mind, as we move forward.

**Comment by BradLarson** [comment]
It's been a while since this issue was raised, and the APIs have changed significantly in that span. Since then, a generalized interface to provide arbitrary weight initializers has been provided and I believe the interface has been made more consistent across the layers.

If there are additional issues not covered by this, feel free to open up a new issue to address them.
