### ISSUE TITLE
Implement requirements for `ElementaryFunctions` as top-level functions

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#199]
Implement all math functions required by the [`ElementaryFunctions`](https://github.com/apple/swift-evolution/blob/master/proposals/0246-mathable.md#proposed-solution) protocol as top-level functions on `Tensor where Scalar: TensorFlowFloatingPoint`.

**Comment by dan-zheng** [comment]
Done in https://github.com/tensorflow/swift-apis/pull/214.
