### ISSUE TITLE
Swift Code Style

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/swift-apis#201]
Can we use [swiftlint](https://github.com/realm/SwiftLint) to standardize the format for the repo? This will avoid reviews about formatting errors and speed up the overall process.

**Comment by rxwei** [comment]
Thanks for the suggestion! This repo is following the [Google Swift Style Guide](https://google.github.io/swift/) with the exception that we use 4-space indentation. This style guide is different from the standard that swiftlint implements. We'd recommend using [swift-format](https://github.com/apple/swift/blob/master/docs/SwiftFormat.md) to format your code, and Swift for TensorFlow toolchains comes with this tool.

**Comment by Mistobaan** [comment]
How do you invoke swift-format? 
`find . -iname \*.swift -exec /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2019-06-06-a.xctoolchain/usr/bin/swift-format -in-place {} +`
returns a lot of changes on the current source code and lots of Parse Errors:
```
Parse error: insufficient indentation of next 2 lines in multi-line string literal
Parse error: should match space here
Parse error: change indentation of these lines to match closing delimiter`
```

Can we add the swift-format step to the docker build?

**Comment by rxwei** [comment]
It is possible that swift-format hasn't been updated for a while and that it no longer works with the latest Swift HEAD, which we are based on. I format manually so I'm not very sure about the state of code formatters. I'll update this issue when there's a better solution.

**Comment by eaplatanios** [comment]
I jus tried using swift-format and it does work but it's not very configurable which causes issues with the current codebase. Google also has [a separate formatter](https://github.com/google/swift/tree/format), but I also tried that and it messes up when using function attributes (which S4TF makes heavy use of). It's also missing a few configuration options to disable some of the more aggressive modifications it's doing. If I get the chance I may try to write all this down and submit an issue at that repo, but it'd also be great if somebody else would like to look into this. :)

**Comment by saeta** [comment]
CC @allevato ^^^

**Comment by rxwei** [comment]
This is happening https://github.com/apple/swift-format/pull/1

**Comment by BradLarson** [comment]
With swift-format now being a mature tool, and with our regular use of if for this and other repositories, it's probably safe to close this out.
