### ISSUE TITLE
Suppress LazyTensor test compilation warnings

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#247]
```console
[46/56] Compiling TensorFlowTests LazyTensorTests.swift
1051
/swift-apis/Tests/TensorFlowTests/LazyTensorTests.swift:79:21: warning: 'let' pattern has no effect; sub-pattern didn't bind any variables
1052
            if case let .symbolic(_) = t.handle {
1053
                    ^~~~~~~~~~~~~~~~
```

**Comment by Shashi456** [comment]
@rxwei there seems to be a few more warnings that pop up in my builds, notably a frozen attribute warning, is that because of my toolchain?

**Comment by bgogul** [comment]
@Shashi456, I get the following warnings, but nothing related to frozen attribute:

`/usr/local/google/home/bgogul/workspace/brain/s4tf/tensorflow-swift-apis/Tests/TensorFlowTests/OperatorTests/BasicTests.swift:470:13: warning: variable 'pb' was never mutated; consider changing to 'let' constant
        var pb: (Tensor<Float>) -> Tensor<Float> = pullback(at: atTensor) { x in
        ~~~ ^
        let
`

**Comment by Shashi456** [comment]
@bgogul, yea I get these warnings as well.

**Comment by bgogul** [comment]
https://github.com/tensorflow/swift-apis/pull/258 fixes these warnings.

**Comment by Shashi456** [comment]
Thanks a lot @bgogul.
