### ISSUE TITLE
unknown attribute 'frozen' @frozen

### ISSUE THREAD

**Issue by MeRajat** [tensorflow/swift-apis#248]
While building swift api package on macos getting this error. 

PS, I am using Xcode 10 | v0.3.1 | April 30, 2019 keychain binding. Let me know what I am missing. 

 `Compile Swift Module 'TensorFlow' (36 sources)
/Users/rajat/Documents/research/swift_tensorflow/swift_dl/swift_dl/Sources/TensorFlow/Core/DataTypes.swift:149:2: error: unknown attribute 'frozen'
@frozen
 ^
/Users/rajat/Documents/research/swift_tensorflow/swift_dl/swift_dl/Sources/TensorFlow/Core/ShapedArray.swift:428:2: error: unknown attribute 'frozen'
@frozen
 ^
/Users/rajat/Documents/research/swift_tensorflow/swift_dl/swift_dl/Sources/TensorFlow/Core/ShapedArray.swift:822:2: error: unknown attribute 'frozen'
@frozen`

**Comment by Shashi456** [comment]
@MeRajat, are you building with nightly?

**Comment by MeRajat** [comment]
That was quick. Thanks :)
