### ISSUE TITLE
Make 'gathering(atIndices:alongAxis:)' generic over 'Int32' and 'Int64'.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#259]
We need to make `Tensor.gathering(atIndices:alongAxis:)` support `Int64` indices, but we cannot do so by making the index tensor's `Scalar` type be generic over `BinaryInteger` because the TensorFlow `Gather` operator (like many other operators that take indices) only supports `Int32` and `Int64` indices.

To resolve this, we should consider adding a `TensorIndexScalar` protocol and conform only `Int32` and `Int64` to it.
```swift
public protocol TensorIndexScalar: BinaryInteger & TenosrFlowScalar {
    ...
}
```

**Comment by eaplatanios** [comment]
We already have `TensorFlowInteger` in `DataTypes.swift` so I could make a PR changing to that. That's what I had done originally but I thought we wanted to stick to using `Int32` for indices everywhere due to the GPU issues that often come up when using `Int64`.
