### ISSUE TITLE
Add a 'dilations:' parameter to 'conv2D(_:filter:strides:padding:)'

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#274]
The raw operator `Raw.conv2D(_:filter:strides:useCudnnOnGpu:padding:explicitPaddings:dataFormat:dilations:)` has a dilations parameter. We should add a parameter to  'conv2D(_:filter:strides:padding:)' so that it becomes 'conv2D(_:filter:strides:padding:dilations:)'.

**Comment by jon-tow** [comment]
I'll take a go at this!

**Comment by rxwei** [comment]
Excellent!

**Comment by Shashi456** [comment]
@rxwei I'll take care of the conv1d and conv3d updates for dilations.

**Comment by rxwei** [comment]
Awesome :)

**Comment by jon-tow** [comment]
@Shashi456 I completed the conv1d updates for dilation b/c it depends on a call to conv2d. Hope that's okay with you?

**Comment by Shashi456** [comment]
@jon-tow cool.

**Comment by eaplatanios** [comment]
Resolved in #275. Thanks @jon-tow!

**Comment by rxwei** [comment]
This change broke a lot of existing code because the newly added parameter does not have a default. We need to add a default argument for dilations.

**Comment by eaplatanios** [comment]
@rxwei Did #277 not resolve this?

**Comment by Shashi456** [comment]
@eaplatanios, I think the parameter also needs to be made optional something like `_ dilations` or else update dilations in other repos like swift models and I think tensorflow/swift

**Comment by rxwei** [comment]
> @rxwei Did #277 not resolve this?

#277 added defaults to layers, but not the op itself.

**Comment by Shashi456** [comment]
@rxwei I'll take this up then. Will get the PR up in a few hours? I'm working on #283 as well.

**Comment by jon-tow** [comment]
Ah geez :frowning: sorry folks. @Shashi456 Why would it also need to be optional if it's given a default?

**Comment by Shashi456** [comment]
@jon-tow to keep the current implementations with conv2d intact

**Comment by Shashi456** [comment]
Ah, Looks like you put the PR already. Alright

**Comment by jon-tow** [comment]
@Shashi456 I thought I'd fix my own wrong doing, rather than have you waste your time on my mistake!

**Comment by Shashi456** [comment]
@jon-tow chill xD.

**Comment by rxwei** [comment]
> Ah geez 😦 sorry folks. @Shashi456 Why would it also need to be optional if it's given a default?

It should not be an optional. Default arguments have clearer semantics in that everything is just a numeric value and is self-explanatory. Also, not using optionals makes it significantly easier for optimizations and lowering later.
