### ISSUE TITLE
Swift build fails on Ubuntu nightly toolchain

### ISSUE THREAD

**Issue by jon-tow** [tensorflow/swift-apis#338]
Invoking `swift build` in the latest master branch fails on the Ubuntu (CUDA 10) nightly toolchain with the following stack dump summary:

```
swift: /swift-base/swift/lib/Serialization/Serialization.cpp:2043: 
         bool swift::serialization::Serializer::isDeclXRef(const swift::Decl *) 
         const: Assertion isa<GenericTypeParamDecl>(D) 
         && "unexpected decl kind"' failed.
Stack dump:  
0.     Program arguments: ...
1.     Swift version 5.1-dev (LLVM af1f73e9e9, Swift bd14b05114)
2.     While running pass #0 SILModuleTransform "SerializeSILPass".
3.     While serializing 'bb0' 
        (at /Projects/s4tf/swift-apis/Sources/TensorFlow/Operators/Basic.swift:412:10)
```

Removing all code related to `batchGathering(atIndices:alongAxis:batchDimensionCount:)` in `Basic.swift` and `Core.swift` resolves the issue but I'm not sure why. 

Can anyone reproduce this on an Ubuntu system? Thanks!

**Comment by rxwei** [comment]
This issue has been fixed by https://github.com/apple/swift/pull/25868 a week ago. Which exact toolchain version are you using (try `swift --version`)?

**Comment by jon-tow** [comment]
@rxwei Yup that was it! I was using a nightly snapshot I downloaded on July 3rd. Didn't think to upgrade. Appreciate the help as always!
