### ISSUE TITLE
Split 'Layer' into two protocols.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#342]
apple/swift#25974 makes it possible to override a protocol requirement with a `@differentiable` attribute that specifies more wrt-parameters.  This makes it possible to remove the `wrt: input` requirement from `callAsFunction(_:)` in the existing `Layer` protocol (#276) so that `Embedding`'s `Input` can be a non-differentiable type `Tensor<Int32>`. In the meantime, we also need a separate protocol which refines the base protocol and requires `callAsFunction(_:)` to be also differentiable with respect to `input`. Of course, this refactoring brings naming questions.

My recommendation is to make `Layer` be the protocol whose `callAsFunction(_:)` is differentiable with respect to both `self` and `input`. I do not have a recommendation for what to call the base `wrt: self`-only protocol, but we should consider some prior art such as `Module`.

**Comment by rxwei** [comment]
```swift
public protocol X: Differentiable {
    associatedtype Input
    associatedtype Output
    @differentiable(wrt: self)
    func callAsFunction(_ input: Input) -> Output
}

public protocol Layer: X where Input: Differentiable {
    @differentiable(wrt: (self, input))
    func callAsFunction(_ input: Input) -> Output
}
```

**Comment by eaplatanios** [comment]
One issue is the use of `Sequential` etc., which will now be limited to `Layer`. We should think a bit about what the expected behavior should be as just directly making this change would make `Embedding` not usable within `Sequential`. I will take a look into this later today.

**Comment by rxwei** [comment]
> One issue is the use of `Sequential` etc., which will now be limited to `Layer`. We should think a bit about what the expected behavior should be as just directly making this change would make `Embedding` not usable within `Sequential`. I will take a look into this later today.

For `Sequential`, you can simply require the first generic parameter to conform to the non-`wrt: input` protocol.

**Comment by eaplatanios** [comment]
Work-in-progress in #346.

**Comment by dan-zheng** [comment]
Done in #346. Thank you @eaplatanios!
