### ISSUE TITLE
Remove 'PointwiseMultiplicative' and 'ElementaryFunctions' requirements from 'Layer'

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#343]
#322 broke some existing code, and these requirements are pretty heavyweight. We should drop these requirements for now.

**Comment by Shashi456** [comment]
Can I take this up? This would mean I'll have to remove layer :PointwiseMultiplicative' and 'ElementaryFunctions, from every layer it was added to ?

**Comment by eaplatanios** [comment]
@rxwei could you possibly add a test with some example code that breaks? It would be great to being in tests for breaking code so we avoid issues in the future and can better think of an appropriate design.

**Comment by rxwei** [comment]
Let's hold off on this change for now. I've experienced breakage in custom defined parameterless layers, but it was simply because they were not using `ParameterlessLayer`. Thanks @Shashi456 for taking a stab!
