### ISSUE TITLE
Bad Memory Leak

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/swift-apis#364]
@rxwei @dan-zheng I get insane memory usage when I try to run some simple reinforcement learning experiments. It looks like there is a memory bug somewhere related to partial applies in auto-diff (purely a guess based on what I saw in the profiler report). Attached is a screenshot which I hope you find helpful in figuring this out:

<img width="1321" alt="Screen Shot 2019-07-14 at 7 25 12 PM" src="https://user-images.githubusercontent.com/1294940/61190643-66ed8900-a66d-11e9-934b-e5babcf6e04c.png">

Note that this is pretty important as it makes it impossible for me to run any experiments currently.

**Comment by rxwei** [comment]
I’m on it.

**Comment by eaplatanios** [comment]
Thanks Richard! I'm also currently compiling the latest apple/swift to see if anything has changed.

**Comment by eaplatanios** [comment]
@rxwei I can confirm the leak is still there even when I use a toolchain built from the latest commit on apple/swift.

**Comment by eaplatanios** [comment]
@rxwei let me know if I can help with this in any way. Although I’m not familiar with memory management during the autodiff pass.

**Comment by rxwei** [comment]
I'm working on a fix [here](https://github.com/rxwei/swift/tree/ownership).

**Comment by eaplatanios** [comment]
Do you have an ETA on when this might be fixed? I may take a look tomorrow but I don't know if it'll be productive given that I'm not familiar with this aspect of the compiler.

**Comment by rxwei** [comment]
I'll try my best to get it land before EOD tomorrow.

**Comment by eaplatanios** [comment]
That's great! Thanks a lot Richard! In that case I may take a shot at one of the other auto-diff bugs in the meantime. I assume we're not ready yet for the `inout` support changes we discussed previously, right?

**Comment by rxwei** [comment]
This week we are aiming to land two things that would allow you to start the `inout` work.

**Comment by eaplatanios** [comment]
That's great news! Thanks Richard!

**Comment by eaplatanios** [comment]
@rxwei so I did some tests after the leak fix PR landed and I noticed that a portion of the leak still exists for me even if I remove all control flow. It's significantly reduced, but still unusable for anything more than toy experiments. I'll try to get an instruments trace uploaded and sent to you if you think that helps.

**Comment by rxwei** [comment]
A trace would be very useful. Note that custom initializer VJPs have leaks ([TF-667](https://bugs.swift.org/browse/TF-667)) and there is a workaround.

**Comment by eaplatanios** [comment]
I see. That workaround requires a lot of changes in swift-apis though. Do you have a rough timeline estimate for the fixes to that leak and the control flow leak? I'll try to get a trace as soon as possible.

**Comment by rxwei** [comment]
Changing swift-apis sounds good and we may actually even keep the workarounds after leaks have been fixed because the workarounds are more efficient.
@dan-zheng is working on the fix and it should land next week.

**Comment by eaplatanios** [comment]
Ok in that case I can make a PR after I also test locally that it resolves the issues I've been seeing. Btw, what do `__owned` and `__shared` imply?

Btw, a nice byproduct of all this digging into the traces is that I discovered a couple of leaks in my retro API. :)

**Comment by eaplatanios** [comment]
I finally traced down the remaining leak in my experiments to a control flow issue. More specifically, I have a differentiable function that contains this loop:
```swift
var newShape = [-1]
for i in outerDimCount..<rank {
  newShape.append(shape[i])
}
return newShape
```
If I wrap this in. `withoutDerivative(at: shape) { ... }` and replace `rank` with `shape.count`, the leak goes away.

**Comment by rxwei** [comment]
> Btw, what do `__owned` and `__shared` imply?

`__owned` implies `@owned` parameter convention, which means the callee consumes the argument. The caller must retain the argument for any additional use of the value other than the callee.

`__shared` implies `@guaranteed` parameter convention, which means the caller is responsible for guaranteeing the lifetime of the argument, while the callee will not cause a change to the argument's reference count when it returns.

Initializer parameters are `__owned` by default. Function parameters are `__shared`  by default.

**Comment by eaplatanios** [comment]
Thanks for the explanation Richard! I opened #378 with the workaround.

**Comment by rxwei** [comment]
A new nightly toolchain has been released with memory leak fixes.

**Comment by eaplatanios** [comment]
I will leave this open for now because even though the latest PR fixed some major issues, there is still the control flow autodiff leak that is causing issues for me.

**Comment by rxwei** [comment]
https://github.com/apple/swift/pull/26355 fixes the rest of memory leaks.
