### ISSUE TITLE
Mention migration instructions in deprecation messages

### ISSUE THREAD

**Issue by burmako** [tensorflow/swift-apis#386]
While trying our some of our models, I encountered warnings along the following lines:

```
main.swift:34:30: warning: 'init(filterShape:strides:padding:dilations:activation:seed:)' is deprecated: This API will be removed after Swift for TensorFlow 0.4.
    var conv1a = Conv2D<Float>(filterShape: (3, 3, 1, 32), activation: relu)
                             ^
```

This message looks a bit confusing since it doesn't explain how to make it go away. I think it would be good if deprecation warnings explained how to migrate away from deprecated APIs.

**Comment by Shashi456** [comment]
Can I work on this o.O?

**Comment by eaplatanios** [comment]
@burmako most of these will just go away as there are new initializers that cover them. I'm not sure why the compiler picks one over the other when both are applicable. @Shashi456 feel free to add pointers to the new initializers in the warning message.
