### ISSUE TITLE
Put expected value after actual value in all uses of 'assertEqual'.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#390]
The expected value should come after the actual value in our tests.

**Comment by Shashi456** [comment]
@rxwei is this final, #153 you said that we should put the expected before the actual value. I'll take this up but should we just make this standard now?

**Comment by rxwei** [comment]
> @rxwei is this final, #153 you said that we should put the expected before the actual value.

No, I actually said the exact opposite:
> XCTAssertEqual(_:_:) expected the second argument (to be the expected value).

The second argument to both `XCTAssertEqual` and `assertEqual` should be the expected value.

**Comment by Shashi456** [comment]
@rxwei so this change is to be done for tests not done? Could you pinpoint any files you specifically saw which needed this?
