### ISSUE TITLE
Auto-Differentiation Bug

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/swift-apis#394]
I opened [TF-681](https://bugs.swift.org/projects/TF/issues/TF-681?filter=allopenissues) for this but thought it may good to post it here too for others to be aware. Consider the following example:

```swift
public struct Test: Layer {
  public var parameters: [Tensor<Float>]

  public init() {
    parameters = [Tensor<Float>](repeating: Tensor<Float>(ones: []), count: 10)
  }

  @differentiable
  public func callAsFunction(_ input: [Tensor<Float>]) -> Tensor<Float> {
    var result = Tensor<Float>(zeros: [])
    for i in 0..<10 {
      result = result + input[i] * parameters[i]
    }
    return result
  }
}

let test = Test()
let input = [Tensor<Float>](repeating: 2 * Tensor<Float>(ones: []), count: 10)
let (loss, gradient) = test.valueWithGradient { test -> Tensor<Float> in
  test(input)
}
dump(gradient)
```

This prints out a gradient of `[0, 0, 0, 0, 0, 0, 0, 0, 0, 2]`, whereas it should be `[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]`.

**Comment by BradLarson** [comment]
It's been a little while, but this appears to have been fixed in https://github.com/apple/swift/pull/28155 (per [TF-681](https://bugs.swift.org/projects/TF/issues/TF-681 ).
