### ISSUE TITLE
Port tensor control flow AD tests

### ISSUE THREAD

**Issue by dan-zheng** [tensorflow/swift-apis#408]
[`test/TensorFlowRuntime/tensor_autodiff_control_flow.swift`](https://github.com/apple/swift/blob/tensorflow/test/TensorFlowRuntime/tensor_autodiff_control_flow.swift) from `apple/swift` needs to be ported to [`Tests/TensorFlowTests/TensorAutoDiffTests.swift`](https://github.com/tensorflow/swift-apis/blob/master/Tests/TensorFlowTests/TensorAutoDiffTests.swift).

This enables removing the deprecated `TensorFlowUnittest` module from `apple/swift` - see https://github.com/apple/swift/pull/26447.

**Comment by rxwei** [comment]
I don’t think this needs to block #26447. These tensor tests are merely using additive arithmetics. Please just make sure the same arithmetics are tested using ‘Tracked’ in the AD suite, and then delete the test file in order to merge #26447.

**Comment by Shashi456** [comment]
@dan-zheng I think this issue can be closed.

**Comment by dan-zheng** [comment]
> @dan-zheng I think this issue can be closed.

Thanks! Closing.
