### ISSUE TITLE
Array of layers no longer able to be differentiate

### ISSUE THREAD

**Issue by sgugger** [tensorflow/swift-apis#411]
Recent changes (since v0.4) have somehow cause a regression on the differentiation of arrays of layers. [Here](https://gist.github.com/sgugger/3e49e5fe63a12654658b3d4918e4b71e) is a minimal reproducer tat used to work in v0.4 but no longer does on the nightlies.

@eaplatanios , @rxwei said to tag you.

**Comment by Shashi456** [comment]
I wonder if this is related to the breakdown into the different protocols.

**Comment by Shashi456** [comment]
@sgugger which one of the notebooks is a minimal reproducer?

**Comment by sgugger** [comment]
Pasted the wrong link sorry, edited.

**Comment by mikowals** [comment]
@sgugger, I think you can just use Array.differentiableReduce() now.  Your extension just becomes:

    extension Array: Layer where Element: Layer, Element.Input == Element.Output {
        // Note: remove the explicit typealiases after TF-603 is resolved.
        public typealias Input = Element.Input
        public typealias Output = Element.Output

        @differentiable
        public func callAsFunction(_ input: Input) -> Output {
              return self.differentiableReduce(input) { $1($0) }
        }
    }

Running with MacOS development toolchain from 2019-07-25 I get a loss of 2.2591848 though the actual result will depend on the random init.

**Comment by sgugger** [comment]
The workaround seems to work, however having a regression on the code of the reproducer isn't necessarily a good sign.

**Comment by eaplatanios** [comment]
@rxwei I believe this is a bug related to apple/swift#25974 where when you specify a custom VJP function something goes wrong with the conditional differentiability checks. When adding `@differentiable(wrt: self)` implicitly to satisfy the `Module` requirement we're passing `None` for the VJP of the added attribute and so maybe this is causing issues? I'm traveling now so I won't be able to take a look for a while.

**Comment by dynamicwebpaige** [comment]
Pinging @pschuh @saeta @dan-zheng - it looks like Jeremy and Sylvain are blocked on this bug. Do we have an ETA to resolve?

**Comment by pschuh** [comment]
We got to the point where we can build the first 7 notebooks as a presubmit. I don't know what that means for this bug.

**Comment by dan-zheng** [comment]
@sgugger: could you please confirm that this is the error you're encountering? [(your reproducer)](https://gist.githubusercontent.com/sgugger/3e49e5fe63a12654658b3d4918e4b71e/raw/65e906e3bd38ae420cf5aaddf68a6a53941ff0c3/array.swift)
```console
$ swift apis-411.swift
apis-411.swift:3:1: error: conditional conformance of type 'Array<Element>' to protocol 'Layer' does not imply conformance to inherited protocol 'Module'
extension Array: Layer where Element: Layer, Element.Input == Element.Output {
^
apis-411.swift:3:1: note: did you mean to explicitly state the conformance like 'extension Array: Module where ...'?
extension Array: Layer where Element: Layer, Element.Input == Element.Output {
^
apis-411.swift:49:20: warning: 'init(filterShape:strides:padding:dilations:activation:seed:)' is deprecated: This API will be removed after Swift for TensorFlow 0.4, please consider using
`init(filterShape:strides:padding:dilations:activation:filterIntializer:biasInitializer:)`
instead.
            return Conv2D(filterShape: (3, 3, allFilters[i], allFilters[i+1]),
                   ^
```

**Comment by pschuh** [comment]
I recognize that error and believe the notebooks have been updated like so:

-extension Array: Layer where Element: Layer, Element.Input == Element.Output {
+extension Array: Layer & Module where Element: Layer, Element.Input == Element.Output {

That is a breakage to swift-apis that didn't make it into the toolchain until after this bug was filed.

**Comment by dan-zheng** [comment]
> @rxwei I believe this is a bug related to [apple/swift#25974](https://github.com/apple/swift/pull/25974) where when you specify a custom VJP function something goes wrong with the conditional differentiability checks.

I believe the fix is much simpler: we must declare `extension Array: Module` explicitly before we declare `extension Array: Layer`. Swift doesn't support "implied conformances", as explained in the error message.

Here's a fixed version of the `Array` conformances in the reproducer:
```
import TensorFlow

extension Array: Module where Element: Module, Element.Input == Element.Output {
    // Note: remove the explicit typealiases after TF-603 is resolved.
    public typealias Input = Element.Input
    public typealias Output = Element.Output
    
    @differentiable(vjp: _vjpApplied)
    public func callAsFunction(_ input: Input) -> Output {
        var activation = input
        for layer in self {
            activation = layer(activation)
        }
        return activation
    }
    
    public func _vjpApplied(_ input: Input)
        -> (Output, (Output.TangentVector) -> (Array.TangentVector, Input.TangentVector))
    {
        var activation = input
        var pullbacks: [(Input.TangentVector) -> (Element.TangentVector, Input.TangentVector)] = []
        for layer in self {
            let (newActivation, newPullback) = layer.valueWithPullback(at: activation) { $0($1) }
            activation = newActivation
            pullbacks.append(newPullback)
        }
        func pullback(_ v: Input.TangentVector) -> (Array.TangentVector, Input.TangentVector) {
            var activationGradient = v
            var layerGradients: [Element.TangentVector] = []
            for pullback in pullbacks.reversed() {
                let (newLayerGradient, newActivationGradient) = pullback(activationGradient)
                activationGradient = newActivationGradient
                layerGradients.append(newLayerGradient)
            }
            return (Array.TangentVector(layerGradients.reversed()), activationGradient)
        }
        return (activation, pullback)
    }
}

extension Array: Layer where Element: Layer, Element.Input == Element.Output {}
```

@sgugger: does this fix unblock you?

**Comment by eaplatanios** [comment]
@dan-zheng Thanks! It's interesting that `Array: Layer` does not imply `Array: Module`. Is that only true for extensions? Because the implication seems to hold when directly declaring structs as conforming to `Layer`.

**Comment by rxwei** [comment]
Conditional conformances don't imply.

**Comment by sgugger** [comment]
Note that there is a new failure on the nightly.
```
//export
extension Array: Module where Element: Module, Element.Input == Element.Output {
    // Note: remove the explicit typealiases after TF-603 is resolved.
    public typealias Input = Element.Input
    public typealias Output = Element.Output

    @differentiable
    public func callAsFunction(_ input: Input) -> Output {
          return self.differentiableReduce(input) { $1($0) }
    }
}

extension Array: Layer where Element: Layer, Element.Input == Element.Output {}
```
now fails with
```
/home/jupyter/git/fastai_dev/swift/FastaiNotebook_01a_fastai_layers/Sources/FastaiNotebook_01a_fastai_layers/01a_fastai_layers.swift:291:53: error: expression is not differentiable
          return self.differentiableReduce(input) { $1($0) }
                                                    ^
/home/jupyter/git/fastai_dev/swift/FastaiNotebook_01a_fastai_layers/Sources/FastaiNotebook_01a_fastai_layers/01a_fastai_layers.swift:291:53: note: member is differentiable only with respect to a smaller subset of arguments
          return self.differentiableReduce(input) { $1($0) }
```

**Comment by eaplatanios** [comment]
@sgugger could you try what @pschuh suggested?

```swift
extension Array: Layer & Module where Element: Module, Element.Input == Element.Output {
    // Note: remove the explicit typealiases after TF-603 is resolved.
    public typealias Input = Element.Input
    public typealias Output = Element.Output

    @differentiable
    public func callAsFunction(_ input: Input) -> Output {
          return self.differentiableReduce(input) { $1($0) }
    }
}
```

**Comment by sgugger** [comment]
This produces the same error as the first one:
``` 
error: <Cell 2>:9:53: error: expression is not differentiable
          return self.differentiableReduce(input) { $1($0) }
                                                    ^

<Cell 2>:9:53: note: member is differentiable only with respect to a smaller subset of arguments
          return self.differentiableReduce(input) { $1($0) }
```
whether in a notebook or trying to build in a module.

Note that this is a fairly recent regression as this code was working on last Thursday's nightlies.

**Comment by rxwei** [comment]
Calling `differentiableReduce(_:_:)` no longer works because `Module` doesn't make the `Input` associated type conform to `Differentiable`, where as `differentiableReduce(_:_:)` requires `Result` to be differentiable. Also, `differentiableReduce(_:_:)` has to require `Result: Differentiable` because that's the only way we can differentiate through a reduction.

**Comment by eaplatanios** [comment]
@rxwei declaring conformance to both `Layer` and `Module` should imply `Input: Differentiable` though. Why is that not happening here?

**Comment by rxwei** [comment]
We are missing a `Element: Layer` constraint. `Element: Module` is not enough because the semantics of reduction naturally requires `Input` to be differentiable.

**Comment by rxwei** [comment]
This works:

```swift
extension Array: Module where Element: Layer, Element.Input == Element.Output {
    public typealias Input = Element.Input
    public typealias Output = Element.Output

    @differentiable(wrt: (self, input))
    public func callAsFunction(_ input: Input) -> Output {
          return self.differentiableReduce(input) { $1($0) }
    }
}
extension Array: Layer where Element: Layer, Element.Input == Element.Output {}
```

**Comment by eaplatanios** [comment]
Oh right...good catch. In that case, this should work:

```swift
extension Array: Layer & Module where Element: Layer & Module, Element.Input == Element.Output {
    // Note: remove the explicit typealiases after TF-603 is resolved.
    public typealias Input = Element.Input
    public typealias Output = Element.Output

    @differentiable
    public func callAsFunction(_ input: Input) -> Output {
          return self.differentiableReduce(input) { $1($0) }
    }
}
```

**Comment by eaplatanios** [comment]
Good catch! Thanks Richard.

**Comment by rxwei** [comment]
Using the composition `Layer & Module` in the conformance clause is good too! I don't even remember when that got supported :)

**Comment by rxwei** [comment]
Here's the fast.ai notebook fix: https://github.com/fastai/swiftai/pull/9.
