### ISSUE TITLE
Can't have a Dataset lazily opening images

### ISSUE THREAD

**Issue by sgugger** [tensorflow/swift-apis#447]
Not too sure if the bug should be filed here on swift-apis or elsewhere, but I'm filing it here just so it's somewhere and tracked.

Currently, having a Dataset containing `StringTensor` will cause a crash when we train to apply a function to open the associated images (lazily). It's a regression since v0.4. The bug occurs in notebook 08 of harebrain, I've put together a minimal reproducer [here](https://github.com/fastai/fastai_dev/blob/master/swift/MinimalDsBug.ipynb).

**Comment by jkrukowski** [comment]
hi @sgugger, like you provided is pointing to your localhost

**Comment by sgugger** [comment]
Oops, thanks for telling me, edited the link above.

**Comment by bgogul** [comment]
PRs that fix this issue: 
   https://github.com/tensorflow/swift-apis/pull/439
   https://github.com/tensorflow/swift-apis/pull/446
   https://github.com/apple/swift/pull/26659

(More to come.)

**Comment by sgugger** [comment]
Confirming the fixes work, thanks a lot!
