### ISSUE TITLE
Problem in comparison operators

### ISSUE THREAD

**Issue by t-ae** [tensorflow/swift-apis#451]
https://github.com/tensorflow/swift-apis/blob/3629ddc49b706df89f89fa3e92e495e6e3f42332/Sources/TensorFlow/Operators/Comparison.swift#L104-L132

Documentation comments says they compare two tensors "lexicographically".
But it seems the code doing is not lexicographical comparison.

I tried to fix it, but soon got stuck.
In the first place, is lexicographical order defined on tensors?

**Comment by rxwei** [comment]
Yeah, it's not doing lexicographical comparison. This comment is legacy and should be removed :)

**Comment by t-ae** [comment]
You mean current implementations are correct?
I feel it's weird that `[0, 1] <= [1, 0]` and `[0, 1] >= [1, 0]` are both `false`.
The usage of its comparability is unclear for me.

**Comment by rxwei** [comment]
The current implementation was added to satisfy `Comparable` conformance (for some other purposes that are no longer valid), and `Comparable` is not necessarily the right thing for `Tensor` to conform to at all. I'd suggest removing the `Comparable` conformance completely.
