### ISSUE TITLE
Is Threading.swift dead code?

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#489]
https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Core/Threading.swift
Looks like dead code to me as I've found no users of anything defined here.

**Comment by bgogul** [comment]
This is not used currently, but might want to keep it around to experiment with parallel training using lazy tensor.

**Comment by rxwei** [comment]
Thanks for the context!
