### ISSUE TITLE
RNN gradients are wrong

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/swift-apis#518]
[This line](https://github.com/tensorflow/swift-apis/blob/27ea161a69ed207c26028286ce751888c6f9a12d/Sources/TensorFlow/Layers/Recurrent.swift#L323) should be `𝛁cell += new𝛁cell` instead. There is also an issue with the initial state initialization to a zeros tensor with batch size 1 that does not broadcast. I don't have time to open a PR right now because I'm traveling but will try to open one once I get a chance.

**Comment by rxwei** [comment]
Nice catch!

**Comment by Shashi456** [comment]
Should I take care of this @eaplatanios

**Comment by eaplatanios** [comment]
@Shashi456 thanks! Feel free to fix the `+=` bug. The initial state issue is a less trivial API design question that I haven't thought about much yet. There are a couple of possible solutions that I used in swift-rl, so I'll try to look into it sometime soon.

**Comment by sgugger** [comment]
I think this has been solved by the two PRs merged. Feel free to reopen if there is still a problem.

**Comment by Shashi456** [comment]
@sgugger the tests against these changes were remaining so I thought we'd keep this PR open. #555, #554 track the tests. But since we have separate issues for them maybe it's okay.

**Comment by sgugger** [comment]
Like you said there are already two issues tracking this. I wanted to do a bit of clean-up, but if anyone feels strongly about this issue remaining open, they can click the button :)
