### ISSUE TITLE
Rename 'transposed(withPermutations:)' to 'transposed(permutation:)'.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-apis#524]
`transposed(withPermutations:)` is not a perfect name because
1. "With" is often considered as a needless word, especially in an argument label where a noun phrase follows. We've been dropping "with" in cases like this for APIs added earlier this year, but we have not revisited `transposed(withPermutations:)` which was introduced since the beginning.
2. The argument is one permutation. So a plural doesn't make sense. Thanks @apaszke-g for pointing this out!

We should deprecate the current API and consider renaming it to `transposed(permutation:)`. A PR is welcome, but it should not be merged until it's discussed in a design review.

**Comment by rahulbhalley** [comment]
I am surprised & happy that @apaszke-g is working on S4TF!! 🎉

**Comment by apaszke-g** [comment]
It's a fake account that belongs to the same person 😄It's a copy of my original account for Google purposes, because I'm (temporarily) visiting the S4TF team to learn more and see how are things going.

**Comment by rahulbhalley** [comment]
It seems like someone is faking unless similar message is conveyed from original account too. 😅

**Comment by Aamir1551** [comment]
Hi could I be assigned to this task, I would love to work on it as a first issue.  Thanks

**Comment by Shashi456** [comment]
@Aamir1551 I'm afraid this is already being worked upon in #527. We have other good first issues in this list.

**Comment by Aamir1551** [comment]
Oh, right, thanks. It said No one assigned, so I thought it still hasn't been worked upon
