### ISSUE TITLE
Testing changes

### ISSUE THREAD

**Issue by vbbphc** [tensorflow/swift-apis#537]
**OS**: Ubuntu 18.04
**Swift version**: 5.1-dev
**Problem**: I'm fairly new to the swift community, so I apologize for this silly question or if it's already been asked before. I've made some additions to the API and `swift build` succeeds. But, I couldn't find any resources that could guide me to use this build to test the changes since `import TensorFlow` goes to the folder in $PATH.  Also, a request for including the above guidelines in the CONTRIBUTING.md would be really helpful.

**Comment by Shashi456** [comment]
I'm not very sure I understand the question, One way to test new api changes is write test cases it helps in unit testing the exact piece of addition, and run `swift test`.

**Comment by vbbphc** [comment]
Ah, thanks a lot @Shashi456 ! That does solve my question.
