### ISSUE TITLE
Make `Tensor.product(squeezingAxes:)` differentiable

### ISSUE THREAD

**Issue by dan-zheng** [tensorflow/swift-apis#545]
[`Tensor.product(squeezingAxes: Tensor<Int32>)`](https://github.com/tensorflow/swift-apis/blob/30a1071d9cdf0322c171899e9c17423fa240e980/Sources/TensorFlow/Operators/Math.swift#L1817) is [currently not `@differentiable`](https://github.com/tensorflow/swift-apis/blob/30a1071d9cdf0322c171899e9c17423fa240e980/Sources/TensorFlow/Operators/Math.swift#L1815).

We should do the following:
* Add the attribute `@differentiable(wrt: self, vjp: _vjpProduct(squeezingAxes:) where Scalar: TensorFlowFloatingPoint)` to `Tensor.product(squeezingAxes: Tensor<Int32>)`.
* Define `func _vjpProduct(squeezingAxes axes: Tensor<Int32>)`.
* Mark `Tensor.product(squeezingAxes: [Int])` and `Tensor.product(squeezingAxes: Int)` as `@differentiable`. No registered derivative is needed because they call `Tensor.product(squeezingAxes: Tensor<Int32>)`.

---

* [TensorFlow reference implementation of `ProdGrad`](https://github.com/tensorflow/tensorflow/blob/72d0facc37e377d89d8034bb825bf0e93a4f810d/tensorflow/cc/gradients/math_grad.cc#L882).
* [Use case from mailing list](https://groups.google.com/a/tensorflow.org/d/msg/swift/9ss6t-neuGE/XqMOA-CQAAAJ).

**Comment by dan-zheng** [comment]
cc @kongzii

**Comment by kongzii** [comment]
Continuing the discussion at [Use case from mailing list](https://groups.google.com/a/tensorflow.org/d/msg/swift/9ss6t-neuGE/XqMOA-CQAAAJ), I will start working on this :)

**Comment by dan-zheng** [comment]
Done in https://github.com/tensorflow/swift-apis/pull/550.
