### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by awav** [tensorflow/swift-apis#567]
Hello everyone,

I have two issues with the TensorFlow build:

1. The first related to 'Experimental' target
<img width="270" alt="Screenshot 2019-11-23 at 11 29 12" src="https://user-images.githubusercontent.com/24483645/69478052-a9765d80-0de5-11ea-9a44-fe2aa74711fe.png">

2. And if I remove 'Experimental' targets, I get this error:
<img width="270" alt="Screenshot 2019-11-23 at 11 29 41" src="https://user-images.githubusercontent.com/24483645/69478059-c7dc5900-0de5-11ea-9793-83e9802f88e4.png">

**Xcode Version 11.2.1 (11B500)
Toolchain: Swift for TensorFlow 0.6 Release
macOS Mojave 10.14.6**

Thanks,
Artem

**Comment by dan-zheng** [comment]
Could you please share how you're opening `swift-apis` in Xcode to produce these errors? Using SwiftPM following works for me:
```console
# Deleting old artifacts may fix SwiftPM hangs.
# rm -rf .build TensorFlow.xcodeproj

$ swift package generate-xcodeproj
$ open TensorFlow.xcodeproj
# Use Legacy Build System: `File > Project Settings > Build System > Legacy Build System`.
```

**Comment by awav** [comment]
@dan-zheng I ran your instructions, now it works for me, thanks!
