### ISSUE TITLE
Convolutional layer kernel size?

### ISSUE THREAD

**Issue by rickwierenga** [tensorflow/swift-apis#572]
Is it possible to specify the kernel size as specified [here](https://keras.io/layers/convolutional/)? I can't figure out how the [Swift code](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Layers/Convolutional.swift) relates to the keras version, but that might be me.

Thanks.

**Comment by Shashi456** [comment]
The current version of the convolution layers mirror the tensorflow apis( You can take a look at them [here](https://www.tensorflow.org/api_docs/python/tf/nn/conv1d).) 

The keras versions are also built on the tensorflow versions, and i think they compute the filter internally which is then passed onto the tensorflow backend. 

The way they calculate the kernel size i.e the filter size is given [here](https://github.com/keras-team/keras/blob/7a39b6c62d43c25472b2c2476bd2a8983ae4f682/keras/layers/convolutional.py#L134):
```python
        input_dim = input_shape[channel_axis]
        kernel_shape = self.kernel_size + (input_dim, self.filters)

        self.kernel = self.add_weight(shape=kernel_shape,
                                      initializer=self.kernel_initializer,
                                      name='kernel',
                                      regularizer=self.kernel_regularizer,
                                      constraint=self.kernel_constraint)
```

Now i think the way thats reflected in our api is, in the case of 1-D convolution:
 ``` swift
filterShape: The 3-D shape of the filter, representing
 ///     (filter width, input channel count, output channel count).
```
where the filter width is akin to the kernel size, the input channel count is the input_dim and the filters parameter is the output channel count.

**Comment by rickwierenga** [comment]
Thank you so much @Shashi456!
