### ISSUE TITLE
Make conv2DBackpropInput public

### ISSUE THREAD

**Issue by t-ae** [tensorflow/swift-apis#596]
`Conv*D` layers have corresponding public functions `conv*D`.
With them we can easily create customized convolutional layers.

On the other hand, `TansposedConv*D` is implemented with internal function `conv2DBackpropInput`.
It makes creating customized transposed convolutional layers hard.

I propose to make it public, or add new `transposedConv2D` function as alias.

**Comment by dan-zheng** [comment]
Sorry for the late reply. I think renaming `conv2DBackpropInput` and making it a public API is reasonable!

---

[`func matmul`](https://github.com/tensorflow/swift-apis/blob/c7afd2dc7c55735e8449256e6e3efc11f6dc5576/Sources/TensorFlow/Operators/Math.swift#L2774) has `transposed: Bool` arguments for transposing `lhs` or `rhs`:
```swift
/// Performs matrix multiplication with another tensor and produces the result.
@inlinable
@differentiable(where Scalar: TensorFlowFloatingPoint)
public func matmul<Scalar: Numeric>(
    _ lhs: Tensor<Scalar>,
    transposed transposeLhs: Bool = false,
    _ rhs: Tensor<Scalar>,
    transposed transposeRhs: Bool = false
) -> Tensor<Scalar> {
    precondition(lhs.rank >= 2, "Input tensors must have at least rank 2")
    precondition(rhs.rank >= 2, "Input tensors must have at least rank 2")
    if lhs.rank > 2 || rhs.rank > 2 {
        // TODO(TF-629): Conjugate to make compatible with the adjoint.
        return _Raw.batchMatMulV2(lhs, rhs, adjX: transposeLhs, adjY: transposeRhs)
    }
    return _Raw.matMul(lhs, rhs, transposeA: transposeLhs, transposeB: transposeRhs)
}
```

Adding a `transposed: Bool = false` argument (or arguments, for both input and filter?) to the existing function `public func conv2D` sounds ideal to me, if possible. @t-ae: would you be interested in looking into this?

Increasing the API surface area with `public func transposedConv2D` is less desirable.

**Comment by t-ae** [comment]
I think `public func transposedConv2D` is worth adding.

1. Both TensorFlow and PyTorch have separate function for transposed conv2D.

TensorFlow:
- https://www.tensorflow.org/api_docs/python/tf/nn/conv2d?version=stable
- https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose?version=stable

PyTorch
- https://pytorch.org/docs/stable/nn.functional.html#conv2d
- https://pytorch.org/docs/stable/nn.functional.html#conv-transpose2d

Users may not expect `conv2D` has `transposed` option.

2. There's already `TransposedConv2D` layer.

If we add the argument `transposed` for `conv2D`, we should add same argument for `Conv2D` and deprecate `TransposedConv2D` to make interface consistent.

**Comment by dan-zheng** [comment]
`conv2DBackpropInput` was renamed to `transposedConv2D` and made public in https://github.com/tensorflow/swift-apis/pull/672.
The `transposedConv2D` API is consistent with TensorFlow/PyTorch.
