### ISSUE TITLE
Conform `TensorShape` to `Collection` protocols

### ISSUE THREAD

**Issue by dan-zheng** [tensorflow/swift-apis#609]
`TensorShape` represents the shape of a tensor. It wraps an `[Int]` and provides additional utilities like `var rank: Int` and `var contiguousSize: Int`.

`TensorShape` should conform to `Collection` and related protocols:
- `Collection`
- `MutableCollection`
- `RandomAccessCollection`
- `RangeReplaceableCollection`

`Collection` protocol requirement implementations should forward to the underlying implementation from `[Int]`.

---

### First steps

You can start by adding empty conformances to `Sources/TensorFlow/Core/TensorShape.swift`, then seeing what compilation errors arise:
```swift
extension TensorShape: Collection {}
```

If you try to compile it, the compiler will produce error messages prompting you to implement the missing `Collection` protocol requirements. Xcode can even fill in protocol requirement skeletons for you.

Use the same technique to implement conformances to other `Collection` protocols.

**Comment by awav** [comment]
Hello @dan-zheng, please assign me to this task. I've started working on it. Thanks!

**Comment by dan-zheng** [comment]
Done in https://github.com/tensorflow/swift-apis/pull/615. Thanks @awav!
https://github.com/tensorflow/swift-apis/pull/599 should be unblocked now: no need for manual `TensorShape.+(_:_:)` definitions.
