### ISSUE TITLE
Input parameter in eye function 

### ISSUE THREAD

**Issue by SumanSudhir** [tensorflow/swift-apis#640]
https://github.com/tensorflow/swift-apis/blob/3ecba9718a1d3c3d91ad90cae36229dd2d6148b5/Sources/TensorFlow/Operators/LinearAlgebra.swift#L148
In TensorFlow, `tf.eye` function takes the `number of columns` and `batch size` as an optional parameter and we don't need to pass the name of a variable while calling it.

Since we are replicating `tf.eye` I am willing to make some minor changes in eye function available in `LinearAlgebra.swift` so that it can take input similar to that of `tf.eye`.

Right now `eye` function in `LinearAlgebra.swift` takes input as:
`var out: Tensor<Float> = eye(rowCount: 5, columnCount: 4, batchShape:[3])` 

After changes the function will be able to take input with number of columns and batch size as optional and user don't need to pass the name of variable:
Eg:

`let x: Tensor<Int32> = eye(4)`
`[[1, 0, 0, 0],`
 `[0, 1, 0, 0],`
 `[0, 0, 1, 0],`
 `[0, 0, 0, 1]]`

`let x: Tensor<Int32> = eye(4,5)`
`[[1, 0, 0, 0, 0],`
 `[0, 1, 0, 0, 0],`
 `[0, 0, 1, 0, 0],`
 `[0, 0, 0, 1, 0]]`

`let x: Tensor<Int32> = eye(4,batch_shape: [1])`
`[[[1, 0, 0, 0],`
  `[0, 1, 0, 0],`
  `[0, 0, 1, 0],`
  `[0, 0, 0, 1]]]`

`let x: Tensor<Int32> = eye(4,5,batch_shape: [1])`
`[[[1, 0, 0, 0, 0],`
  `[0, 1, 0, 0, 0],`
  `[0, 0, 1, 0, 0],`
 ` [0, 0, 0, 1, 0]]]`

`let x: Tensor<Float32> = eye(4,5,batch_shape: [1])`
`[[[1.0, 0.0, 0.0, 0.0, 0.0],`
  `[0.0, 1.0, 0.0, 0.0, 0.0],`
  `[0.0, 0.0, 1.0, 0.0, 0.0],`
  `[0.0, 0.0, 0.0, 1.0, 0.0]]]`

`let x: Tensor<Float32> = eye(4,5,batch_shape: [1,2])`
`[[[[1.0, 0.0, 0.0, 0.0, 0.0],`
   `[0.0, 1.0, 0.0, 0.0, 0.0],`
   `[0.0, 0.0, 1.0, 0.0, 0.0],`
   `[0.0, 0.0, 0.0, 1.0, 0.0]],`
`                                       `
  `[[1.0, 0.0, 0.0, 0.0, 0.0],`
  ` [0.0, 1.0, 0.0, 0.0, 0.0],`
  ` [0.0, 0.0, 1.0, 0.0, 0.0],`
   `[0.0, 0.0, 0.0, 1.0, 0.0]]]]` 

@dan-zheng @Shashi456 if making number of columns, batch size and not passing the variable name before calling it looks good to you then I will open PR for this issue

**Comment by Shashi456** [comment]
IMO, although the idea of not having any explicit variable name sound good I think it makes for readable code, and more clarity as to what you are doing. I'm okay with either direction, but the current API also makes sense to me.

**Comment by SumanSudhir** [comment]
@Shashi456 why you removed test case for eye function ??

**Comment by Shashi456** [comment]
@SumanSudhir maybe you are not looking for the right file. You can look at the test case [here](https://github.com/tensorflow/swift-apis/blob/f8a4c3996f6f55499eddb7f1bcfd6b27bfab0b47/Tests/TensorFlowTests/OperatorTests/MatrixTests.swift#L124).

**Comment by SumanSudhir** [comment]
Oh sorry, I was looking in LinearAlgebraTest file.

**Comment by t-ae** [comment]
It's good to have argument labels in Swift.
But the labels of `eye` looks not so good.

`columnCount` is a bit obscure in `eye(rowCount: 3)`, and it is much more obscure when it comes to `eye(rowCount: 3, columnCount: nil)`.

Why don't we have separate functions, say,
```swift
public func eye<Scalar: Numeric>(
    size: Int,
    batchShape: [Int] = []
) -> Tensor<Scalar>
```
and 
```swift
public func eye<Scalar: Numeric>(
    rowCount: Int,
    columnCount: Int,
    batchShape: [Int] = []
) -> Tensor<Scalar>
```
?

**Comment by SumanSudhir** [comment]
We don't need to pass `columnCount: nil` as it is an optional parameter, I found it later. Only some minor changes are needed to match it with `tf.eye`, not to pass the name of variable rows and columns while using it.

**Comment by t-ae** [comment]
> We don't need to pass `columnCount: nil` as it is an optional parameter,

I know, of course.
The problem is that currently we **can** pass `columnCount: nil`.

The functions I wrote above doesn't allow `columnCount` to be `nil` so it is much clearer API.

I'm not sure if so many S4TF users want strictly TensorFlow-like API.
I always find argument label useful when compare Swift to Python, Kotlin, etc.
