### ISSUE TITLE
Is it possible to convert Tensor to Data?

### ISSUE THREAD

**Issue by rickwierenga** [tensorflow/swift-apis#647]

**Comment by rickwierenga** [comment]
This works:

```swift
Data(Tensor<UInt8>(someTensor).array.scalars)
```

But I am not sure if this is the fastest/most elegant solution.

**Comment by BradLarson** [comment]
I don't believe the above is what you'll want for encoding a Tensor as Data. I think you are downcasting each element of the Tensor from whatever its type is to UInt8, losing information in the process. You're not getting the byte representation of the value, you're squeezing the value into a single byte.

This isn't the cleanest, but here's an approach for a Tensor<Float> that grabs the representative in-memory bytes for a Tensor. This matches the byte representation in a serialized TensorFlow checkpoint, for example:

```swift
let scalars = tensor.array.scalars

var data = Data()
scalars.withUnsafeBufferPointer { (ptr) in
    ptr.baseAddress!.withMemoryRebound(
        to: UInt8.self, capacity: ptr.count * MemoryLayout<Float>.size
    ) {
        data.append($0, count: ptr.count * MemoryLayout<Float>.size)
    }
}
```
