### ISSUE TITLE
No such module 'TensorFlow’ with v0.7-rc1 on Xcode 11

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift-apis#665]
On Xcode `import TensorFlow` statement produces an error: `No such module 'TensorFlow’` with New Build System. Although this error still does not go away when using this toolchain with Legacy Build System, instead of New Build System, but the project does builds and still fails to run in Xcode 11. 

On terminal, after setting the `PATH` variable to this toolchain and running the program with `swift main.swift` command executes correctly. 

I’m on macOS Catalina 10.15.3 and Xcode 11.3.1 (11C504).

**Comment by dan-zheng** [comment]
Sorry about the Xcode error!

Could you please see if this local patch to `/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.7.xctoolchain/Info.plist` fixes the issue?
```diff
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
 	<key>Aliases</key>
 	<array>
 		<string>Swift for TensorFlow</string>
 	</array>
 	<key>CFBundleIdentifier</key>
 	<string>com.google.swift.20200210</string>
 	<key>CompatibilityVersion</key>
 	<integer>2</integer>
 	<key>CompatibilityVersionDisplayString</key>
 	<string>Xcode 8.0</string>
 	<key>CreatedDate</key>
 	<date>2020-02-10T18:05:31Z</date>
 	<key>DisplayName</key>
 	<string>Swift for TensorFlow 0.7 Release</string>
 	<key>OverrideBuildSettings</key>
 	<dict>
 		<key>ENABLE_BITCODE</key>
 		<string>NO</string>
 		<key>SWIFT_DEVELOPMENT_TOOLCHAIN</key>
 		<string>YES</string>
 		<key>SWIFT_DISABLE_REQUIRED_ARCLITE</key>
 		<string>YES</string>
 		<key>SWIFT_LINK_OBJC_RUNTIME</key>
 		<string>YES</string>
 		<key>SWIFT_USE_DEVELOPMENT_TOOLCHAIN_RUNTIME</key>
 		<string>YES</string>
 	</dict>
 	<key>ReportProblemURL</key>
 	<string>https://bugs.swift.org/</string>
 	<key>ShortDisplayName</key>
 	<string>Swift for TensorFlow 0.7 Release</string>
 	<key>Version</key>
-	<string>swift-tensorflow-RELEASE-0.7</string>
+	<string>5.0.20200210</string>
 </dict>
 </plist>
```

**Comment by rahulbhalley** [comment]
After making this modification if I try to select v0.7-rc1 toolchain from `Xcode > Preferences > Components` then Xcode gives an error: "invalid Info.plist (plist or signature have been modified)".

And on terminal when I run `swift` it produces the following error.
```
dyld: Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.7.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB
  Reason: image not found
zsh: abort      swift
```

**Comment by dan-zheng** [comment]
I pushed a new 0.7 macOS toolchain to https://storage.googleapis.com/swift-tensorflow-artifacts/releases/v0.7/rc1/swift-tensorflow-RELEASE-0.7-osx.pkg.

Could you please install it and verify whether the issues (Python 3 linker error, Xcode errors) are fixed?

**Comment by rahulbhalley** [comment]
Thanks, now it works great on Xcode!
