### ISSUE TITLE
Encapsulate _Raw.resizeNearestNeighbor within function or Layer

### ISSUE THREAD

**Issue by BradLarson** [tensorflow/swift-apis#670]
As part of [issue #225 on swift-models](https://github.com/tensorflow/swift-models/issues/225), we are attempting to remove references to _Raw functions in swift-models in favor of higher-level abstractions. One of the remaining references to _Raw comes in the use of   `_Raw.resizeNearestNeighbor(images:, size:)` and  `_Raw.resizeNearestNeighborGrad(grads:, size:)` within FastStyleTransfer/Utility/Resize.swift.

This function and its matching gradient could be placed within either a free function (probably the preferred approach) or a Layer to abstract away the underlying implementation here, then the matching model in swift-models can be updated to use that new abstraction. Additionally, tests should be added in swift-apis to verify correct behavior of the operation. This should be relatively straightforward to implement.

**Comment by t-ae** [comment]
There are `resizeArea`, `resizeNearestNeighbor`, `resizeBilinear`, `resizeBicubic` in `_Raw`.
Soon or later we will have their non-`_Raw` APIs too.

TensorFlow has single resize API that can specify the method to use.
https://www.tensorflow.org/api_docs/python/tf/image/resize
I think it'll be good to follow this way.

**Comment by BradLarson** [comment]
Fixed by PR #706. Thanks again, @t-ae!

**Comment by Kshitij09** [comment]
@BradLarson threre's still one [reference](https://github.com/tensorflow/swift-models/blob/a9f4f79ab91de9419ac47921149ff1a257d197f8/FastStyleTransfer/Models/TransformerNet.swift#L173) to FastStyleTransfer/Utility `resizeNearestNeighbour` which should be replaced with high level resize API of #706. Should I make necessary change or it'll be auto updated?
