### ISSUE TITLE
Breaking down the Layers.swift file

### ISSUE THREAD

**Issue by Shashi456** [tensorflow/swift-apis#69]
So the layer.swift file is long and since we are actively working on adding layers #54 , it might make more sense to break down the file into convolutions, pooling, recurrence and other such files. Might make the code overall more readable. 
@rxwei @tanmayb123 Thoughts?

**Comment by rxwei** [comment]
Sounds reasonable to me. Feel free to send a PR.

**Comment by eaplatanios** [comment]
Also started breaking down the operators file in #70 , so it may make sense to follow a similar pattern and create a `Layers` directory.
