### ISSUE TITLE
Problem with MaxPool3D input dimensions

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift-apis#690]
I wrote a little code snippet below.

```swift
let input1D = Tensor<Float>(randomNormal: [128, 2]).rankLifted()
let maxpool1D = MaxPool1D<Float>(poolSize: 2, stride: 2, padding: .same)
let output1D = maxpool1D(input1D)
print("\(input1D.shape) -> \(output1D.shape)")

let input2D = Tensor<Float>(randomNormal: [128, 128, 3]).rankLifted()
let maxpool2D = MaxPool2D<Float>(poolSize: (2, 2), strides: (2, 2), padding: .same)
let output2D = maxpool2D(input2D)
print("\(input2D.shape) -> \(output2D.shape)")

let input3D = Tensor<Float>(randomNormal: [128, 128, 3]).rankLifted()
let maxpool3D = MaxPool3D<Float>(poolSize: (2, 2, 2), strides: (2, 2, 2), padding: .same)
let output3D = maxpool2D(input3D)
print("\(input3D.shape) -> \(output3D.shape)")
```

Why does not `MaxPool3D` take a 4D data as input? When I pass `[1, 64, 128, 128, 3]` as input it throws an error: `Fatal error: tensor_in_shape must have 2 spatial dimensions.` I don't even understand where `64` should've come (current position or after 3?) given that it's a temporal dimension size.
<hr>

**Output**
```swift
[1, 128, 2] -> [1, 64, 2]
[1, 128, 128, 3] -> [1, 64, 64, 3]
[1, 128, 128, 3] -> [1, 64, 64, 3]
```

The output above feels `MaxPool3D` works same under-the-hood as `MaxPool2D` 'cause it successfully downsamples the same size tensor as input for `MaxPool2D`. 

And please improve the error message. It sounds like it was meant for `MaxPool2D` only. For `MaxPool1D` and `MaxPool3D` it should've used 1 temporal and 3 spatio-temporal dimensions, respectively, in fatal error message.

**Comment by Shashi456** [comment]
@rahulbhalley you are calling `let output3D = maxpool2D(input3D)`, can you run `maxpool3D(input3D)` ?

**Comment by rahulbhalley** [comment]
Oh s---. I'm sorry, it's my typo not a bug. Thank you. Will look more clearly into code before jumping into open an issue. Really sorry.
