### ISSUE TITLE
Conform `Array` to `Module` and `Layer`

### ISSUE THREAD

**Issue by dan-zheng** [tensorflow/swift-apis#699]
Add a conditional conformance: `extension Array: Layer where Element: Layer`.

An `Array` of `Layer`s is a `Layer` that applies each element layer in sequence to an input to produce an output. The `callAsFunction` method calls [`differentiableReduce`](https://github.com/apple/swift/blob/7c34fa581b4c30df092190bbe067570a638ac2f0/stdlib/public/Differentiation/DifferentiationSupport.swift#L1279-L1285), with the input as the initial value.

I think this definition is correct, but I haven't tested it:
```swift
import TensorFlow

extension Array: Module where Element: Layer, Element.Input == Element.Output {
    public typealias Input = Element.Input
    public typealias Output = Element.Output

    @differentiable
    public func callAsFunction(_ input: Input) -> Output {
        differentiableReduce(input) { $1($0) }
    }
}

extension Array: Layer where Element: Layer, Element.Input == Element.Output {}
```
Please add this to the library and add tests! [Motivating mailing list thread here.](https://groups.google.com/a/tensorflow.org/g/swift/c/JfJYs0x6vpA)

If you'd like to work on this, please comment and I'll add you as the assignee.

**Comment by dan-zheng** [comment]
Comment: it's pretty slick that you can make `Array` a `Layer` in just 9 lines.
The power of differentiable programming + protocol-oriented programming!

**Comment by SumanSudhir** [comment]
@dan-zheng can I take up this issue as I need a similar module for one of my models?

**Comment by rahulbhalley** [comment]
Oh s---! @SumanSudhir bro I wanted this! You been too quick to get assigned! 🤪

Just kidding. Looking towards your work. 😃

**Comment by SumanSudhir** [comment]
Sorry, my exam was going on, so I didn't spend time on it that day

**Comment by saeta** [comment]
Reassigning to @dabrahams who had some thoughts on design here. Thanks!

**Comment by s1ddok** [comment]
Just tried the proposed approach by @dan-zheng - very convenient but unfortunately doesn't work for now. Using array for my resblocks results in strange errors like that:

```Fatal error: Inputs to operation ReluGrad of type ReluGrad must have the same size and shape.  Input 0: [] != input 1: [1,64,64,256]: file /swift-base/tensorflow-swift-apis/Sources/TensorFlow/Bindings/EagerExecution.swift, line 30
/bin/sh: 53: Fatal: not found
```

hardcoding each block in the property solves the issue. 

Just wanted to let you know of potential problems. Hopefully the feature makes it into release.

**Comment by dabrahams** [comment]
As noted in https://github.com/tensorflow/swift-apis/pull/673#discussion_r394652982 I don't think the specific feature requested in this issue is quite right and there are alternatives that would be more powerful/useful.  Back to @dan-zheng to reply or repurpose this issue or close it and open a new one.

**Comment by austinjones** [comment]
I ran into this issue - would be great to add to the library.  It took a bunch of Github sluething to find a way to run an input through many identical layers.

Or, if an array extension doesn't work, maybe a SequentialArray type could wrap this behavior, so it'd be discoverable in the API docs?

**Comment by rahulbhalley** [comment]
Any updates on this one?

**Comment by saeta** [comment]
Hi @rahulbhalley ! Thanks for checking in on this one. @dabrahams and @dan-zheng have updated https://github.com/tensorflow/swift-apis/pull/708 to reflect our current thinking. Feedback on that PR is welcome!

**Comment by rahulbhalley** [comment]
Somehow the [mailing list discussion post](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/JfJYs0x6vpA) link is now changed.

**Comment by dan-zheng** [comment]
I'm closing this issue, since directly conforming `Array` to `Layer` is no longer the direction we're pursuing.

A fresh issue https://github.com/tensorflow/swift-apis/issues/1021 tracks the new layer wrapper type approach and provides rationale for it.

---

To users: if you need to use an `Array: Layer` conformance in the short-term before #1021 is done, feel free to add it locally to your codebase. A sample conformance definition is available [here](https://github.com/tensorflow/swift-apis/issues/699#issue-571826837).
