### ISSUE TITLE
Swift for TensorFlow on Kaggle

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift-apis#701]
Hi all!

I was wondering if S4TF team have any plans to [somehow] allow Swift for TensorFlow on Kaggle. I think that’s gonna be an amazing platform in addition to Google Colab! It will boost even more adoption of S4TF since Kaggle platform is purely focused on ML/DL challenges (even Google Brain team post challenges there!). Also now Kaggle has TPU pods too. It’ll allow DS/ML/DL researchers/ [DL] competitive programmer to experiment and use Swift right on the competition platform. 

I wish someone please do it. I will really really love to experience this.

**Comment by 8bitmp3** [comment]
I reckon after v1.0 /swift-jupyter/ (@marcrasi) could be ported to kaggle's notebooks for people to start playing with. Colab is a good playground right now.

**Comment by dan-zheng** [comment]
I'm not sure our team currently has the resources or interest in supporting Swift for TensorFlow on Kaggle. I don't know what's involved, but that sounds like a fun potential community contribution! From someone who does care about Kaggle 🙂

**Comment by rahulbhalley** [comment]
> I reckon after v1.0 /swift-jupyter/ (@marcrasi) could be ported to kaggle's notebooks for people to start playing with.

@8bitmp3 I wonder what is the true plan for S4TF v1.0. 

Since Swift is super hackable with extensions, conditional conformances, and other features, I think putting S4TF on Kaggle, in its current state, will still be an amazing idea as team has already stated many times that S4TF is ready for research (I think someone have even deployed style transfer model with S4TF). Furthermore, [swift-models](https://github.com/tensorflow/swift-models) already demonstrate a wide range of NNs that can be built with it.

**Comment by BradLarson** [comment]
To add on to what Dan said, we've had conversations with the Kaggle team and they're aware of Swift for TensorFlow. They're great people to work with, and have had some really neat recent initiatives, including the [new availability of TPUs on Kaggle](https://www.kaggle.com/c/flower-classification-with-tpus) or the fascinating [Abstraction and Reasoning Challenge](https://www.kaggle.com/c/abstraction-and-reasoning-challenge/overview).

It's both a matter of what we have the bandwidth to support (as Dan said), as well as what we feel comfortable launching with. Kaggle competitors will want something they can use quickly and easily to solve problems vs. other frameworks, and we still have a few components to build out and under-the-hood performance improvements to make to be desirable over other frameworks in competitions.

I absolutely think we'll get there, but I'd like for us to have the best first impression with Kaggle competitors as we can. Give us a little time to build out some of what we're working on now, and I think we'll be in a much better place to introduce ourselves to competitors.

**Comment by rahulbhalley** [comment]
Oh yes, definitely @BradLarson. First impression gotta be straight 🔥.

I’ve seen on r/deeplearning & r/machinelearning subreddits that people are less receptive to Swift in the world of machine learning whereas people on r/swift are more interested in it (maybe they find it more comfortable to transit than current Python users; probably cuz Python users feel like ‘we write anything and it works (dynamic type system: only `object`s)’ and in Swift they’ll have to be more careful). 

I admit Swift have to prove a little bit but will take off, of course. 🚀

**Comment by BradLarson** [comment]
I think we had a good enough discussion about the reasons for holding off on this for now, so I'll close this issue out until we're ready to re-examine this.
