### ISSUE TITLE
Question: Two Tensor<Float> arguments but differentiable w.r.t. only one

### ISSUE THREAD

**Issue by t-ae** [tensorflow/swift-apis#705]
```swift
@differentiable(wrt: input)
func myFunc(
    input: Tensor<Float>,
    input2: Tensor<Float>
) -> Tensor<Float> {
    input
}

@derivative(of: myFunc) // Function result's 'pullback' type does not match 'myFunc(input:input2:)'
func vjpMyFunc(
    input: Tensor<Float>,
    input2: Tensor<Float>
) -> (value: Tensor<Float>, pullback: (Tensor<Float>)->Tensor<Float>) {
    let value = myFunc(input: input, input2: input2)
    return (value, { v in v })
}
```

`myFunc` is not differentiable w.r.t. `input2`, so I thought pullback of `vjpMyFunc` is this.
But compiler requires pullback to be `(Tensor<Float>)->(Tensor<Float>, Tensor<Float>)`.
How can I make `myFunc` differentiable w.r.t. only `input`?

**Comment by dan-zheng** [comment]
Use `@derivative(of: myFunc, wrt: input)`.
`@derivative` accepts a `wrt:` differentiability parameters clause, just like `@differentiable`.

```swift
import TensorFlow

@differentiable(wrt: input)
func myFunc(input: Tensor<Float>, input2: Tensor<Float>) -> Tensor<Float> {
    input
}

@derivative(of: myFunc, wrt: input)
func vjpMyFunc(input: Tensor<Float>, input2: Tensor<Float>) -> (
    value: Tensor<Float>, pullback: (Tensor<Float>) -> Tensor<Float>
) {
    let value = myFunc(input: input, input2: input2)
    return (value, { v in v })
}
```

The [differentiable programming manifesto](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#derivative-functions) has more info on the `@derivative` attribute.
Hope this helps!
