### ISSUE TITLE
Can't compile with latest toolchain

### ISSUE THREAD

**Issue by t-ae** [tensorflow/swift-apis#714]
From latest toolchain (Development Snapshots/Xcode/February 29, 2020) I get compilation error below.

```
Compiling for macOS 10.10, but module 'PythonKit' has a minimum deployment target of macOS 10.13: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-02-29-a.xctoolchain/usr/lib/swift/macosx/PythonKit.swiftmodule/x86_64.swiftmodule
```

It requires to write `platforms` like swift-models.
https://github.com/tensorflow/swift-models/blob/78565015dce1c7dd1cb2b905d19f80d5585536f7/Package.swift#L8-L10

Or is it a compiler-side bug?

**Comment by compnerd** [comment]
This isn't a compiler-side issue.  This is a build configuration setting.  You can see in the build configuration [here](https://github.com/apple/swift/blob/tensorflow/utils/swift_build_support/swift_build_support/products/pythonkit.py#L53) that we explicitly set the minimum deployment version to 10.13.  If we do not specify one, it will be the version of the build host.  If there is a strong reason, we could try to see if we could lower that requirement, but that should be done with an intention of supporting the minimum deployment target and with testing that the functionality behaves properly on the target.

**Comment by t-ae** [comment]
@compnerd 
Thank you for clarification.

> If there is a strong reason,

No. But now all S4TF/S4TF projects have to define `paltforms` in Package.swift.
I think it'll be good if `swift package init` automatically write it.

**Comment by dan-zheng** [comment]
For now, I avoided this error with the [2020-03-03 macOS toolchain](https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-2020-03-03-a-osx.pkg) by running `swift build -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13`.
