### ISSUE TITLE
`AnyLayer` type erasure

### ISSUE THREAD

**Issue by s1ddok** [tensorflow/swift-apis#723]
I've recently completed my first S4TF project - [pix2pix implementation](https://github.com/s1ddok/pix2pix-s4tf). It went more or less smooth, but one thing I couldn't workaround is huge generic types produced by recursive U-Net creation. 

In particular it results in [such things](https://github.com/s1ddok/pix2pix-s4tf/blob/44a807ba2ef53304640b44d5aca9454ebff7fef3/Sources/pix2pix/Generator.swift#L5), not a great problem, but still something I would love to avoid. I tried to introduce something like `AnyLayer` with regular type erasure approaches, but failed. 

Is a team awared of any approaches to this? Is this possible to implement? Is it on a roadmap maybe? I think it is very important for models that structure can be parameterized by run-time values (e.g. number of downsampling layers in particular).

**Comment by dabrahams** [comment]
None of this solves your immediate problem (Dan's already promised to try to do that 😉) but:

For the particular models you express concern about at the end, we might benefit most from having a layer that repeats a layer or group of layers a dynamic number of times.  That could avoid the performance costs of total type erasure while providing the flexibility you're looking for.

Also, there are various API techniques we could use to avoid users having to write out these long types and instead deduce them.

**Comment by s1ddok** [comment]
@dan-zheng have you had a chance to take a closer look on this one?

**Comment by dan-zheng** [comment]
@s1ddok: so sorry for the delay!

`struct AnyLayer<Input: Differentiable, Output: Differentiable` is straightforward to implement, but is currently blocked by a compiler bug: SR-12641. I'm looking into the compiler bug now and hope to share an update within a week!

**Comment by dan-zheng** [comment]
The blocking compiler bug (SR-12641) has been fixed. I'll start a PR for `AnyLayer` within the week.

**Comment by s1ddok** [comment]
@dan-zheng cool! I will rewrite my U-Net to have a run-time defined then!

**Comment by BradLarson** [comment]
Given that AnyLayer was introduced in [swift-models PR #651](https://github.com/tensorflow/swift-models/pull/651), I think it's safe to close this out.
