### ISSUE TITLE
Dataset that doesn't fit into RAM

### ISSUE THREAD

**Issue by s1ddok** [tensorflow/swift-apis#770]
Am I correct that current Dataset implementation expects the whole dataset to be loaded into RAM? Is there a on-demand IO support right now, or one have to implement it?

**Comment by brettkoonce** [comment]
That is correct, currently everything gets loaded into memory.

Per the SIG meeting yesterday, sounded like the XLA codepath would pull in some batch logic/do a better job with GPU memory usage.  @asuhan can you (if possible) provide any more details?

**Comment by BradLarson** [comment]
We're working to deprecate the TensorFlow Dataset type in place of the [Batcher](https://github.com/tensorflow/swift-models/tree/master/Batcher) architecture that is being tested and evolved in swift-models. We should be removing all references there to Dataset in favor of this pretty soon. The Batcher structure should allow for on-demand loading of larger datasets (see the Imagenette example implementation for a demonstration).

**Comment by BradLarson** [comment]
To follow on to this, as of [PR #418 in swift-models](https://github.com/tensorflow/swift-models/pull/418), all TensorFlow.Dataset usage has been replaced with the Batcher architecture. We will be deprecating the use of TensorFlow.Datasets. Batcher supports handling datasets that do not entirely fit into memory, and allows for lazy-loading data on demand, so we shouldn't be limited to just what we can fit into memory any more.

As Brett said, we are seeing decent improvements in on-device RAM usage with the XLA-based X10 backend on GPUs vs. the previous TensorFlow eager backend. That's a separate issue, but it will help as well.
