### ISSUE TITLE
TensorFlow Probability

### ISSUE THREAD

**Issue by pedronahum** [tensorflow/swift-apis#785]
Hi all,

Is there a JIRA ticket or issue that is tracking what is needed in order to bring probabilistic reasoning and analysis to Swift for TensorFlow?

#562 tracks "Layer 0" (ie, tf.linalg), but I havent seen something similar for other Layers. 

Thanks!

**Comment by texasmichelle** [comment]
We do not currently have anything tracking that problem. It's interesting, but large in scope and likely deserves its own home outside of S4TF.
