### ISSUE TITLE
Add a test that checks outputShapes are set after materialization.

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#896]
Imported from JIRA https://bugs.swift.org/browse/TF-702

Type: | Bug | Priority: | Minor
-- | -- | -- | --
Reporter: | Gogul Balakrishnan | Assignee: | Gogul Balakrishnan
Resolution: | Unresolved | Votes: | 0
Labels: | LazyTensor

In some cases, we may not be able to identify the shape of a `LazyTensorOperation` until after it is materialized. We should add a test that checks the `outputShapes` property is set correctly after materialization.

**Comment by dan-zheng** [comment]
I think we can close this. We're not using [TF shape inference infrastructure](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Core/LazyTensorShapeInference.swift) any more.
