### ISSUE TITLE
Remove _TFCOpSetDeviceFromScope

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#900]
Imported from JIRA https://bugs.swift.org/browse/TF-531

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Eugene Burmako | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | None

See https://github.com/apple/swift/pull/25023#discussion_r287119117.

**Comment by dan-zheng** [comment]
I think this issue is obsolete, I'm not sure what is `_TFCOpSetDeviceFromScope`. We can open a new issue with more details if necessary.
