### ISSUE TITLE
Generalize TFTensorOperation when opaque return types are available

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#901]
Imported from JIRA https://bugs.swift.org/browse/TF-522

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Gogul Balakrishnan | Assignee: | Gogul Balakrishnan
Resolution: | Unresolved | Votes: | 0
Labels: | None

https://github.com/tensorflow/swift-bindings/pull/30 removed the ability to specify the type of TensorHandle in a `TensorOperation` to avoid having to use opaque return types. When opaque return types are generally available, we should revisit this.

**Comment by dan-zheng** [comment]
I think we can close this, since the [TF-Eager-based lazy tensor](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Core/LazyTensorOperation.swift) is no longer under development.
