### ISSUE TITLE
Virtualize Runtime Interface to enable experimentation with different execution modes

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#902]
Imported from JIRA https://bugs.swift.org/browse/TF-502

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Gogul Balakrishnan | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | None

The overall idea is to have swift side abstractions, namely GraphOperation and  ExecutionBackend. We should also design it in a way that different backends can interact with each other. e.g., we should be able to mix eager execution and tracing

**Comment by dan-zheng** [comment]
I think we can close this, since the [TF-Eager-based lazy tensor](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Core/LazyTensorOperation.swift) is no longer under development.
