### ISSUE TITLE
Slow scalar performance even using withDevice(.cpu)

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#903]
Imported from JIRA https://bugs.swift.org/browse/TF-450

Type: | Bug | Priority: | Minor
-- | -- | -- | --
Reporter: | Chris Lattner | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | Performance

There is something odd going on. Consider this code from the fast.ai tutorial:
```
func TensorMatmul(_ a: Tensor<Float>, _ b: Tensor<Float>) -> Tensor<Float> {
var res = Tensor(repeating: Float(0.0), shape: [a.shape[0], b.shape[1]])

for i in 0 ..< a.shape[0] {
for j in 0 ..< b.shape[1] {
for k in 0 ..< a.shape[1]

{ res[i, j] += a[i, k] * b[k, j] }
}
}
return res
}

time()

{ _ = TensorMatmul(m1, m2) }
Running this for me is something like 7s on a GPU, 14s when using

time() {
withDevice(.cpu)

{ _ = TensorMatmul(m1, m2) }
}
```
but is apparently much much faster when turning the GPU off with CUDA_VISIBLE_DEVICES="" in the environment. We need to figure out what is going on here.

**Comment by BradLarson** [comment]
A lot has changed in the APIs and backends since this was filed, and I doubt the performance characteristics of these operations are still the same concern as they were then.
