### ISSUE TITLE
Revisit the heuristic to allow materialization during shape inference in lazy tensor

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#918]
Imported from JIRA: https://bugs.swift.org/browse/TF-765

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Gogul Balakrishnan | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | LazyTensor

TF Shape functions can use the `input_tensors` of a TF op during shape inference. This is useful in computing shapes of operators like `Fill`.

Right now, we allow materialization of all `Pack` operator during shape inference as it is used for creating tensors from array literals. This can cause problems by triggering premature materialization. We should revisit this heuristic:

  - Be selective about when we trigger materialization.

 - Possibly trigger materialization for other operators during shape inference

 

Relevant PR: https://github.com/tensorflow/swift-apis/pull/453/files

**Comment by ematejska** [comment]
Could you review, given recent X10 work?

**Comment by asuhan** [comment]
@ematejska I don't think any of it applies anymore, we don't have problems with retrieving shapes. Inference is handled by the XLA builder itself.
