### ISSUE TITLE
Implement shape inference for resource/variant handles.

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#921]
Imported from JIRA: https://bugs.swift.org/browse/TF-695

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Gogul Balakrishnan | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | LazyTensor

Implement shape inference for resource and variant handle. e.g., tf.dataset uses resources/variant handles. TF shape inference infrastructure supports this via output_handle_shape_and_types argument to `shape_inference::InferenceContext`.

Implement this in TFE_InferShapes and use in swift-apis.

**Comment by dan-zheng** [comment]
I think we can close this. We're not using TF shape inference infrastructure any more.
