### ISSUE TITLE
Make LazyTensors thread safe.

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#922]
Imported from JIRA: https://bugs.swift.org/browse/TF-693

Type: | Task | Priority: | Minor
-- | -- | -- | --
Reporter: | Gogul Balakrishnan | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | LazyTensor

Currently, LazyTensor implementation is not thread safe. e.g. We should prevent materialization of LazyTensorOperations in different threads from interfering with each other.We may be able to use the LazyTensorOperationsTracker data structure that keeps track of the `LazyTensorOperations` created in the current thread to solve this issue.
--

**Comment by ematejska** [comment]
Could you review, given recent X10 work?

**Comment by asuhan** [comment]
Completely different implementation now and we run it multi-threaded all the time.
