### ISSUE TITLE
Debugging and Profiling Tools for Lazy Tensors

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#933]
Imported from JIRA https://bugs.swift.org/browse/TF-588

Type: | Story | Priority: | Minor
-- | -- | -- | --
Reporter: | Anthony Platanios | Assignee: | Gogul Balakrishnan
Resolution: | Unresolved | Votes: | 0
Labels: | LazyTensor

It'd be great to add support for tracking the materialization of lazy tensors and being able to profile (i.e., measure materialization frequency, redundancy, overhead, etc.).

**Comment by asuhan** [comment]
With x10, we've added several such tools: https://github.com/tensorflow/swift-apis/blob/master/Sources/x10/swift_bindings/doc/TROUBLESHOOTING.md#more-debugging-tools.

**Comment by ematejska** [comment]
Closing this out as a result.
