### ISSUE TITLE
GRUCell internal tensors undersized for inputSize != hiddenSize

### ISSUE THREAD

**Issue by lindyhoptrader** [tensorflow/swift-apis#936]
The internal weight and hidden state matrices for GRUCell are undersized and fail at matmul if inputSize != hiddenSize.

They should be initialized more like this:

@noDerivative public var stateShape: TensorShape {
    //[1, updateWeight1.shape[0]]
     updateWeight1.shape
  }

/// Creates a `GRUCell` with the specified input size and hidden state size.
  ///
  /// - Parameters:
  ///   - inputSize: The number of features in 2-D input tensors.
  ///   - hiddenSize: The number of features in 2-D hidden states.
  public init(
    inputSize: Int,
    hiddenSize: Int,
    weightInitializer: ParameterInitializer<Scalar> = glorotUniform(),
    biasInitializer: ParameterInitializer<Scalar> = zeros()
  ) {
    let inputWeightShape = TensorShape([inputSize, hiddenSize])
    let hiddenWeightShape = TensorShape([hiddenSize, hiddenSize])
    let gateBiasShape = TensorShape([hiddenSize])
    self.updateWeight1 = weightInitializer(inputWeightShape)
    self.updateWeight2 = weightInitializer(hiddenWeightShape)
    self.updateBias = biasInitializer(gateBiasShape)
    self.resetWeight1 = weightInitializer(inputWeightShape)
    self.resetWeight2 = weightInitializer(hiddenWeightShape)
    self.resetBias = biasInitializer(gateBiasShape)
    self.outputWeight1 = weightInitializer(inputWeightShape)
    self.outputWeight2 = weightInitializer(hiddenWeightShape)
    self.outputBias = biasInitializer(gateBiasShape)
  }

Here's another detailed python GRUCell implementation for reference, showing hiddenWeightShapes as square 2D hidden X hidden matrices:

https://github.com/dennybritz/rnn-tutorial-gru-lstm/blob/master/gru_theano.py

testGRU() in LayerTests.swift should be supplemented with an example where inputSize != hiddenSize

Also should check LSTMCell for possibility of similar tensor sizing errors.

**Comment by dan-zheng** [comment]
Hi @lindyhoptrader,

It's a bit hard to understand your issue without more context. If you feel `GRUCell` initialization is in need of a fix, could you please turn your changes above into a PR and update tests?

**Comment by kongzii** [comment]
I noticed this too. Also, If I test outputs against reference implementation in Python, it does not match.

@dan-zheng Can you please assign me the issue? I am working on the fix and test again refernce implementation in Keras and I will do PR soon.
