### ISSUE TITLE
Bidirectional RNN

### ISSUE THREAD

**Issue by kongzii** [tensorflow/swift-apis#943]
This is follow up to discussion https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/xuspcIrHLoQ with @dan-zheng .

My current (naive) implementation looks like this:

```swift
public struct BiLSTM: Layer {
    @noDerivative 
    public let activation: Activation

    var forward, backward: RNN<LSTMCell<Float>>

    public typealias Activation = @differentiable(Tensor<Float>) -> Tensor<Float>

    public init(inputSize: Int, hiddenSize: Int, activation: @escaping Activation = identity) {
        precondition(hiddenSize % 2 == 0)
        let hiddenSizePerLSTM = hiddenSize / 2

        self.activation = activation
        forward = RNN(LSTMCell<Float>(inputSize: inputSize, hiddenSize: hiddenSizePerLSTM))
        backward = RNN(LSTMCell<Float>(inputSize: inputSize, hiddenSize: hiddenSizePerLSTM))
    }

    @differentiable
    public func callAsFunction(_ input: Tensor<Float>) -> Tensor<Float> {
        let forwardSequence = input.unstacked(alongAxis: 1)
        let backwardSequence = input.reversed(inAxes: 1).unstacked(alongAxis: 1)

        let forwardCells = forward(forwardSequence)
        let backwardCells = backward(backwardSequence)

        return activation(
            forwardCells[input.shape[1] - 1].hidden
                .concatenated(with: backwardCells[input.shape[1] - 1].hidden, alongAxis: 1)
        )
    }
}
```

So basically like dan said, layer is storing two LSTMs and forwarding input through both of them. I believe this is the way how bidirectional LSTMS are done, but please correct me if there is a better alternative.

I read many ways about what to do with outputs from two LSTM: concatenate like above, sum, multiplication, difference. I wonder if it is better to provide only one or allows users to choose between modes at layer init?

Also, it would be probably best to do this in a more universal way, so all RNN layers will be able to be bidirectional?

Could somebody please give me some hints to kick-start my implementation in swift-apis way?

Thanks.

**Comment by dan-zheng** [comment]
Thank you Peter for creating this issue!



> Also, it would be probably best to do this in a more universal way, so all RNN layers will be able to be bidirectional?

**Comment by kongzii** [comment]
@dan-zheng Thanks! Could you please assign me the issue? It seems that I can not do it as a Contributor.

**Comment by kongzii** [comment]
Merged in https://github.com/tensorflow/swift-apis/pull/946.
