### ISSUE TITLE
Initial `PrintX10Metrics()` call must be early in code execution

### ISSUE THREAD

**Issue by mikowals** [tensorflow/swift-apis#954]
Placement of the first `PrintX10Metrics()` call seems very important to producing X10 metric information.

I created [an example](https://colab.research.google.com/github/mikowals/swift/blob/printx10metrics/docs/site/tutorials/introducing_x10.ipynb) based on the X10 tutorial with only cells necessary for X10 training.  Using "run all" will produce no X10 metric messages though `PrintX10Metrics()` is called in the last code cell at the end of every epoch.

Uncommenting `PrintX10Metrics()` line just below `import TensorFlow` and using `restart and run all` will print both a blank metric report after that cell and subsequent complete metric reports at the end of each epoch.  Without restarting no metric reports are produced.

Also, if the initial `PrintX10Metrics()` call is later, as in the commented code just before the model is created and moved to and X10 device, no reports will be produced.

**Comment by asuhan** [comment]
I strongly suspect this is an output buffering issue with `PrintX10Metrics`.

**Comment by asuhan** [comment]
@mikowals I found a workaround and applied it to your notebook: add `setenv("TF_CPP_MIN_LOG_LEVEL", "0", /*override*/ 1)` early on (I've added it to the third code cell). Outside Colab, you can just `export TF_CPP_MIN_LOG_LEVEL=0` before launching your executable. This fixes the problem, here's why:

The TF logging system checks that [variable](https://github.com/tensorflow/tensorflow/blob/843f3da02df95e95593af625091646e3ed49b8d6/tensorflow/core/platform/default/logging.cc#L163) before [deciding](https://github.com/tensorflow/tensorflow/blob/843f3da02df95e95593af625091646e3ed49b8d6/tensorflow/core/platform/default/logging.cc#L195) whether to log or not. We [set](https://github.com/tensorflow/swift-apis/blob/763fa17a91bdc6d241d123a923dbc0ea1229d808/Sources/TensorFlow/Core/Runtime.swift#L211) it early on, unless it's already set.

**Comment by mikowals** [comment]
Closing this as I think this was just my mistake in not setting the log level correctly to log INFO.  

I did get confused by the log level being set correctly if I put the `PrintX10Metrics()` call early enough but that seems more like a feature than a bug.
