### ISSUE TITLE
How to get target batch variable using TrainingEpochs

### ISSUE THREAD

**Issue by kushukla** [tensorflow/swift-apis#961]
I am trying to use the new `TrainingEpochs` API mentioned at https://github.com/tensorflow/swift-apis/pull/864 URL. I have two question, highlighted in the below code.

```swift
// Sample Data with two features, one target and 15 samples
let x_train = Tensor<Float>(Array(1...30).map {Float($0)}).reshaped(to: TensorShape([15, 2]))
let y_train = Tensor<Float>(Array(1...15).map {Float($0*2)}).reshaped(to: TensorShape([15, 1]))

// QUESTION 1: This seems to be boilerplate code. Can it be avoided in this scenario?
let rawItems = 0..<15
let dataset = rawItems.lazy.map { x_train[$0] }

// Training loop
let epochs = TrainingEpochs(samples: dataset, batchSize: 5)
for (epoch, epochBatches) in epochs.prefix(2).enumerated() {
    print("Epoch: ", epoch)
    for batch in epochBatches {

        let batch = batch.collated
        print("train X batch: ", batch)
        
        // QUESTION 2: How to get the corresponding target variable from y_train?
        // print("train Y batch", ??)
        
      }
}
```

**Q1:** Is there a way to avoid `rawItems.lazy.map` in case there is no preprocessing required?
**Q2:** How to get the corresponding target variable for the batch from y_train?

Thanks in advance,
Kunal

**Comment by kushukla** [comment]
I tried something like below:
```swift
let dataset = rawItems.lazy.map { (x_train[$0], y_train[$0]) }
```
However, it throws following error
```
(aka '(Tensor<Float>, Tensor<Float>)') cannot conform to 'Collatable'; only struct/enum/class types can conform to protocols
        let batch = batch.collated
```

**Comment by sgugger** [comment]
For your first question, no you don't need to use `.lazy.map` when there is no processing. The `Epochs` API works with any kind of collection.

Your approach in your last message is the right one to get the targets, you just need to use the struct `LabeledData` in swift-models: you can't conform a tuple to a protocol in swift (for now) so we need to add a struct to do this and can't just use a tuple of tensors.
```
let dataset = rawItems.lazy.map { LabeledData(data: x_train[$0], label: y_train[$0])) }
```
will work and let you use `.collated`.
You can import `LabeledData` from `ModelSupport` in swift-models, or just copy its [code](https://github.com/tensorflow/swift-models/blob/master/Support/LabeledData.swift) in your project.

**Comment by kushukla** [comment]
Thanks!! @sgugger that worked as expected
