### ISSUE TITLE
Support argsort()

### ISSUE THREAD

**Issue by ddxgz** [tensorflow/swift-apis#964]
I didn't argsort() in Swift API, neither in `_Raw`. It is available in [Tensorflow's Python API](https://www.tensorflow.org/api_docs/python/tf/argsort?hl=ca). Is there any plan for this?

**Comment by dabrahams** [comment]
This is just `a.indices.sorted { a[$0] < a[$1] }`.  Does that work for you?

**Comment by ddxgz** [comment]
> This is just `a.indices.sorted { a[$0] < a[$1] }`. Does that work for you?

Thanks. My current workaround is for a tensor `t`,
```
let a = t[0..., 0].array
let s = t[0..., 0].scalars
let idxSorted = a.indices.sorted { s[$0] < s[$1] }
```
I don't know if there's a better way.

**Comment by dabrahams** [comment]
Why bother with `a`?  Does this not work?

```swift
let idxSorted = s.indices.sorted { s[$0] < s[$1] }
```

**Comment by asuhan** [comment]
FWIW, depending on the size of the tensor and whether if it's on an accelerator, doing it with `.sorted` might be expensive.

**Comment by dabrahams** [comment]
@ddxgz Please let us know if using `s.indices.sorted` works for you and performs adequately.

Thanks!

**Comment by ddxgz** [comment]
@dabrahams `s.indices.sorted` works for me. Maybe it was a typo that caused me switch to use the additional array. Thanks!

@asuhan I came to Swift recently and is still experimenting with simple algorithms to get familiar with the language and Swift for Tensorflow, not yet with big data size or complex models. 

What I'm playing around is to find a handy n-dimensional array type to use in Swift, as `ndarray` in numpy. As for now I haven't found a mature enough project providing this. After reading through the [design document](https://github.com/tensorflow/swift/blob/master/docs/DesignOverview.md#user-apis-tensor-shapedarray-etc), I realize that what I'm after should be `ShapeArray` other than `Tensor` for n-d array manipulation.

**Comment by dabrahams** [comment]
@ddxgz Thanks; closing for now!
