### ISSUE TITLE
device mismatch in pullback of Tensor(_, deviceAndPrecisionLike:)

### ISSUE THREAD

**Issue by mikowals** [tensorflow/swift-apis#973]
This relates to behaviour seen in #965.

I made a small reproducer of the device mismatch.

    import TensorFlow

    @differentiable(wrt: t)
    func scalarTensor(t: Tensor<Float>) -> Tensor<Float> {
        Tensor<Float>(1.0, deviceAndPrecisionLike: t)
    }
    let device = Device.defaultXLA
    let x = Tensor<Float>(0, on: device)
    let (val, pullback) = valueWithPullback(at: x, in: scalarTensor)
    pullback(Tensor<Float>(1, on: device))
    // Fatal error: Op must have the same backend type: TF_EAGER vs XLA:

I can work around by either using `withoutDerivative(at: t)` or I can add a custom derivative like this:

    extension Tensor where Scalar: TensorFlowFloatingPoint {
        @derivative(of: init(_:deviceAndPrecisionLike:)) 
        static func vjpDeviceAndPrecisionLike(_ value: Scalar, deviceAndPrecisionLike tensor: Tensor
            ) -> (value: Tensor, pullback: (Tensor) -> (Scalar, Tensor)
        ) {
            return (value: Tensor(value, deviceAndPrecisionLike: tensor), pullback: { 
                ($0.scalarized(), Tensor(0, deviceAndPrecisionLike: tensor))
            })
        }
    }

Declaring `init(_:deviceAndPrecisionLike:)` differentiable only with respect to the first argument also seems sensible but that then just forces the use of `withoutDerivative()` in the second argument to avoid having an undefined pullback.  

I am happy to make a pull request but I am not sure what is a preferred solution.  Maybe there is also another obvious way to fix this that I have overlooked.

**Comment by dabrahams** [comment]
Fixed by #999
